try{
var s_Kia,s_Lia,s_wi,s_Mia,s_xi;s_D("sy42");var s_yi=function(a){s_I(this,a,0,2,null,null)};s_f(s_yi,s_H);s_yi.prototype.jh=function(){return s_K(this,1)};var s_Nia={};var s_zi=s_b,s_Ai=s_dd(0),s_Bi=s_dd(0),s_Ci=s_dd(0),s_Oia=function(a,b){window.scrollBy(a,b)},s_Di=function(a,b){window.scrollTo(a,b)},s_Ei=s_ed,s_Fi=s_ed,s_Pia=s_b,s_Qia=s_db.match(/ GSA\/([.\d]+)/),s_Gi=s_Qia?s_Qia[1]:"";s_Mia=(s_xi=!!s_Qia)&&0<=s_Ha(s_Gi,"4");s_wi=s_xi&&0<=s_Ha(s_Gi,"5.2");s_Lia=s_xi&&0<=s_Ha(s_Gi,"5.7");s_Kia=s_xi&&0<=s_Ha(s_Gi,"4.3")&&0>s_Ha(s_Gi,"4.5");

s_C("sy42");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy53");var s_Hi=function(){if(document.body){var a=s_Td(document.body).top;s_Hi=s_dd(a);return a}return 0},s_Ria=s_b,s_Sia=s_b;
s_C("sy53");s_E();
}catch(e){_DumpException(e)}
try{
s_D("em3");
s_C("em3");s_E();
}catch(e){_DumpException(e)}
try{
s_D("em1");
s_C("em1");s_E();
}catch(e){_DumpException(e)}
try{
s_D("em2");
s_C("em2");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy55");var s_qj={Yoa:{},tha:function(a,b,c){var d=c?1:0;if(!s_ha(0!=d?"velour.loadJsInterfaceWithFlags":"velour.loadJsInterface"))return s_jf("No Velour.");a in s_qj.Yoa||(s_qj.Yoa[a]={});c=s_qj.Yoa[a];if(c[b])return c[b];var e=s_lf(),f=0!=d?window.velour.loadJsInterfaceWithFlags(a,b,d):window.velour.loadJsInterface(a,b),d="google.velourCb."+a+"."+b;s_sa(d,{onSuccess:function(){e.resolve(f.getResult())},onFailure:function(){e.reject(a+"."+b+" failed to load: "+f.getError().getMessage())}});f.setCallback(d);
return c[b]=e.$},call:function(a,b,c,d){for(var e=[a,b,!1],f=2;f<arguments.length;f++)e.push(arguments[f]);return s_qj.vYa.apply(s_qj,e)},vYa:function(a,b,c,d,e){for(var f=s_qj.tha(a,b,c),g=[],k=4;k<arguments.length;k++)g.push(arguments[k]);return f.then(function(a){return a[d]?a[d].apply(a,g):s_jf(d+" not found")})}};

s_C("sy55");s_E();
}catch(e){_DumpException(e)}
try{
s_D("em0");
s_C("em0");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy328");var s_k5a=!1,s_l5a=null,s_n5a=function(){var a=s_m5a;s_8c(window,"beforeunload",function(){s_k5a||s_l5a.set("isn",a)})};if(s_xi){var s_l5a=s_7f("session","isn"),s_m5a,s_o5a,s_p5a,s_q5a=s_Xg("isn").split(":");s_p5a=s_q5a[0];s_o5a=s_q5a[1];(s_m5a=s_p5a?s_ub(s_o5a,s_p5a):null)&&s_n5a()};

s_C("sy328");s_E();
}catch(e){_DumpException(e)}
try{
s_D("aa");
s_C("aa");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy82");
s_C("sy82");s_E();
}catch(e){_DumpException(e)}
try{
var s_0ma=function(a){return a.ka||(a.ka=a.ha())},s_1ma=function(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};s_D("sy81");var s_tk=function(a){s_cd.call(this);this.headers=new s_se;this.yla=a||null;this.vp=!1;this.tla=this.Qe=null;this.TX="";this.TP=0;this.JR="";this.EQ=this.Fwa=this.rga=this.Uoa=!1;this.p7=0;this.zv=null;this.lT="";this.zCa=this.YA=!1};s_f(s_tk,s_cd);s_tk.prototype.Dd=null;var s_2ma=/^https?$/i,s_3ma=["POST","PUT"],s_4ma=[],s_uk=function(a,b,c,d,e,f,g){var k=new s_tk;s_4ma.push(k);b&&k.listen("complete",b);k.pn("ready",k.xTa);f&&k.xT(f);g&&(k.YA=g);k.send(a,c,d,e);return k};
s_tk.prototype.xTa=function(){this.dispose();s_2a(s_4ma,this)};s_tk.prototype.xT=function(a){this.p7=Math.max(0,a)};s_tk.prototype.UN=function(a){this.lT=a};
s_tk.prototype.send=function(a,b,c,d){if(this.Qe)throw Error("p`"+this.TX+"`"+a);b=b?b.toUpperCase():"GET";this.TX=a;this.JR="";this.TP=0;this.Uoa=!1;this.vp=!0;this.Qe=this.koa();this.tla=this.yla?s_0ma(this.yla):s_0ma(s_pea);this.Qe.onreadystatechange=s_c(this.qLa,this);try{this.Fwa=!0,this.Qe.open(b,String(a),!0),this.Fwa=!1}catch(f){this.Ni(5,f);return}a=c||"";var e=this.headers.clone();d&&s_Uca(d,function(a,b){e.set(b,a)});d=s_Xa(e.Pf(),s_5ma);c=s_ga.FormData&&a instanceof s_ga.FormData;!s_Ya(s_3ma,
b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.Qe.setRequestHeader(b,a)},this);this.lT&&(this.Qe.responseType=this.lT);"withCredentials"in this.Qe&&this.Qe.withCredentials!==this.YA&&(this.Qe.withCredentials=this.YA);try{s_6ma(this),0<this.p7&&((this.zCa=s_7ma(this.Qe))?(this.Qe.timeout=this.p7,this.Qe.ontimeout=s_c(this.Ij,this)):this.zv=s_ag(this.Ij,this.p7,this)),this.rga=!0,this.Qe.send(a),this.rga=!1}catch(f){this.Ni(5,f)}};
var s_7ma=function(a){return s_Nb&&s_Xb(9)&&s_oa(a.timeout)&&s_a(a.ontimeout)},s_5ma=function(a){return s_Sea("Content-Type",a)};s_tk.prototype.koa=function(){return this.yla?this.yla.$():s_Lf()};s_tk.prototype.Ij=function(){"undefined"!=typeof s_iaa&&this.Qe&&(this.JR="Timed out after "+this.p7+"ms, aborting",this.TP=8,this.dispatchEvent("timeout"),this.abort(8))};s_tk.prototype.Ni=function(a,b){this.vp=!1;this.Qe&&(this.EQ=!0,this.Qe.abort(),this.EQ=!1);this.JR=b;this.TP=a;s_8ma(this);s_9ma(this)};
var s_8ma=function(a){a.Uoa||(a.Uoa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};s_tk.prototype.abort=function(a){this.Qe&&this.vp&&(this.vp=!1,this.EQ=!0,this.Qe.abort(),this.EQ=!1,this.TP=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),s_9ma(this))};s_tk.prototype.Ha=function(){this.Qe&&(this.vp&&(this.vp=!1,this.EQ=!0,this.Qe.abort(),this.EQ=!1),s_9ma(this,!0));s_tk.Ba.Ha.call(this)};
s_tk.prototype.qLa=function(){this.isDisposed()||(this.Fwa||this.rga||this.EQ?s_$ma(this):this.tib())};s_tk.prototype.tib=function(){s_$ma(this)};
var s_$ma=function(a){if(a.vp&&"undefined"!=typeof s_iaa&&(!a.tla[1]||4!=a.EK()||2!=a.getStatus()))if(a.rga&&4==a.EK())s_ag(a.qLa,0,a);else if(a.dispatchEvent("readystatechange"),4==a.EK()){a.vp=!1;try{a.isSuccess()?(a.dispatchEvent("complete"),a.dispatchEvent("success")):(a.TP=6,a.JR=a.Lta()+" ["+a.getStatus()+"]",s_8ma(a))}finally{s_9ma(a)}}},s_9ma=function(a,b){if(a.Qe){s_6ma(a);var c=a.Qe,d=a.tla[0]?s_b:null;a.Qe=null;a.tla=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},
s_6ma=function(a){a.Qe&&a.zCa&&(a.Qe.ontimeout=null);s_oa(a.zv)&&(s_bg(a.zv),a.zv=null)};s_=s_tk.prototype;s_.dd=function(){return!!this.Qe};s_.isSuccess=function(){var a=this.getStatus(),b;if(!(b=s_1ma(a))){if(a=0===a)a=s_ce(1,String(this.TX)),!a&&s_ga.self&&s_ga.self.location&&(a=s_ga.self.location.protocol,a=a.substr(0,a.length-1)),a=!s_2ma.test(a?a.toLowerCase():"");b=a}return b};s_.EK=function(){return this.Qe?this.Qe.readyState:0};
s_.getStatus=function(){try{return 2<this.EK()?this.Qe.status:-1}catch(a){return-1}};s_.Lta=function(){try{return 2<this.EK()?this.Qe.statusText:""}catch(a){return""}};s_.Hm=function(){try{return this.Qe?this.Qe.responseText:""}catch(a){return""}};var s_vk=function(a,b){if(a.Qe)return a=a.Qe.responseText,b&&0==a.indexOf(b)&&(a=a.substring(b.length)),s_ye(a)};
s_tk.prototype.$q=function(){try{if(!this.Qe)return null;if("response"in this.Qe)return this.Qe.response;switch(this.lT){case "":case "text":return this.Qe.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.Qe)return this.Qe.mozResponseArrayBuffer}return null}catch(a){return null}};s_tk.prototype.getResponseHeader=function(a){if(this.Qe&&4==this.EK())return a=this.Qe.getResponseHeader(a),null===a?void 0:a}; s_tk.prototype.getAllResponseHeaders=function(){return this.Qe&&4==this.EK()?this.Qe.getAllResponseHeaders():""};var s_wk=function(a){return s_na(a.JR)?a.JR:String(a.JR)};

s_C("sy81");s_E();
}catch(e){_DumpException(e)}
try{
var s_xk=function(a){for(var b in a)return a[b]};s_D("sy80");var s_ana=function(a){function b(a,b){c.push(encodeURIComponent(b)+":"+encodeURIComponent(a))}var c=[];a instanceof Map?a.forEach(b):s_fb(a,b);return c.join(",")};var s_bna="authuser deb e esrch expflags expid fesp gl hl host hotel_dates hotel_ds noj ogdeb opti opts optq optt mergelabel mlp plugin rlst skew_host source_ip ssl_dbg st tbcp tbs tcfs useragent uuld uule v".split(" "),s_cna=function(){return""},s_fna=function(a,b,c,d,e,f,g,k,l){b=s_dna(b,d,e,f,g,k);l&&(b.q=encodeURIComponent(l));s_tb(b,c);return s_cna(b)+"/async/"+a+s_ena(b)},s_gna=function(a,b,c,d,e,f,g,k){var l="/search",m=b.q,n=b.start;delete b.q;delete b.start;b=s_dna(b,d,e,f,g,!1);void 0!=
m&&(b.q=encodeURIComponent(m));void 0!=n&&(b.start=n);k&&(b.sns="1",l="/s");b.asearch=a;s_tb(b,c);return l+s_ena(b)},s_dna=function(a,b,c,d,e,f){var g={};f&&(g.dfsl=1);(a=s_ana(a))&&(g.async=a);b&&(a=new s_Re,s_Cg(a,b),(b=s_Ve(a))&&(g.vet=s_he(b,"vet")));d?g.ved=d:g.ei=c?c:google.kEI;null!=e&&(g.lei=e);s_g(s_bna,function(a){var b=s_Xg(a);b&&(g[a]=encodeURIComponent(b))});c=s_Zg(new s_gg);s_tb(g,s_xg(c));g.yv=2;return g},s_ena=function(a){if(s_nb(a))return"";var b=[];s_fb(a,function(a,d){b.push(d+ "="+a)});return"?"+b.join("&")};
var s_hna=function(a){return Object.keys(a).map(function(b){return encodeURIComponent(b)+"."+a[b]}).join(",")},s_ina=function(a){var b=Object.keys(a).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a[b])}).join("&");b&&(b="&"+b);return b},s_jna=function(a){a=s_hna(a);var b={};return b.rt=a,b};
var s_yk=function(){this.ka=this.$=0},s_kna=function(){var a=window.performance;return a&&a.now?a.now():s_e()};s_yk.prototype.start=function(){this.$=this.$||s_kna()};s_yk.prototype.pause=function(){this.ka=this.$?this.ka+s_kna()-this.$:this.ka;this.$=0};var s_Ak=function(){var a=s_zk;return Math.round(a.ka+(a.$?s_kna()-a.$:0))};s_yk.prototype.reset=function(){this.ka=this.$=0};
var s_lna=!1,s_zk=new s_yk,s_mna=new function(){var a={};this.$=void 0===a.path?"gen_204":a.path},s_Bk=function(a,b,c,d,e,f,g,k,l){s_zk=new s_yk;s_zk.start();b._fmt=c;var m=s_nna(a);a=s_fna(a,b,l||{},d,void 0,e,k,g,f);m.rt.ub=s_Ak();return s_ona(a,c,m)},s_pna=function(a,b,c,d,e,f,g,k){b._fmt="jspb";b.q=c;s_zk=new s_yk;s_zk.start();c=s_nna(a);a=s_gna(a,b,d||{},e,void 0,f,g,k);c.rt.ub=s_Ak();return s_ona(a,"jspb",c)},s_ona=function(a,b,c){var d=s_lf();c.rt.fr=s_Ak();s_uk(a,function(a){var e=a.target,
g=e.Hm();c.rt.bs=g.length;if("complete"==a.type&&e.isSuccess())if(c.rt.st=s_Ak(),s_qna(c),s_ua(g,")]}'\n")&&(g=g.substr(5)),"json"==b){var k;try{JSON?k=JSON.parse(g):k=s_ze(g)}catch(l){d.reject(l)}s_qa(k)&&(k=s_xk(k),a=k.__err__,s_a(a)&&d.reject(a));d.resolve(k)}else d.resolve(g);else c.rt.ft=s_Ak(),s_qna(c),d.reject(void 0)},void 0,void 0,void 0,void 0,!1);return d.$},s_qna=function(a){if(s_a(window.navigator.sendBeacon)&&s_lna){a=Object.assign(a,s_jna(a.rt));a=Object.assign({},a);var b="";s_a(a.ct)&& (b=a.ct,delete a.ct);a=s_ina(a);a=google.logUrl(b,a,void 0,void 0,s_mna.$);null!=window.navigator.sendBeacon&&navigator.sendBeacon(a)}},s_nna=function(a){var b={};b.astyp=a;b.rt={};return b};

s_C("sy80");s_E();
}catch(e){_DumpException(e)}
try{
var s_rna=function(a,b){return s_Ta(b,function(a,b){return a.Ef(b)},a)},s_sna=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);s_n(a)}},s_tna=function(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1},s_una=function(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return s_tna(b,a)},s_vna=function(a){if(!a)return{};var b={};s_g(a.split(","),function(c){c=c.split(":");2!=c.length&&
google.ml(Error("T"),!1,{_sn:"as_badCtx",cxt:a});b[decodeURIComponent(c[0])]=decodeURIComponent(c[1])});return b},s_wna=function(){var a=s_Dg(),a=s_9j(a);if(!a.q){var b=s_9j(s_9e());b.q&&(a.q=b.q,s_ie().hash=s_Vka(a))}},s_Ck=function(a){null!=a&&s_Nd(a)&&s_Qb&&(a.style.display="none",s_Kb(a.offsetHeight),a.style.display="")},s_xna=function(a){a>s_$e?s_af=1:a<s_$e&&(s_af=2)},s_yna=function(a,b){for(var c=a.search(s_Nca),d=0,e,f=[];0<=(e=s_Mca(a,d,b,c));){d=a.indexOf("&",e);if(0>d||d>c)d=c;e+=b.length+
1;f.push(s_Aa(a.substr(e,d-e)))}return f},s_zna=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(s_Nb&&!s_Yb(9)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?s_tna(a,b):!c&&s_Mc(e,b)?-1*s_una(a,b):!d&&s_Mc(f,a)?s_una(b,a):(c?a.sourceIndex:e.sourceIndex)-
(d?b.sourceIndex:f.sourceIndex)}d=s_lc(a);c=d.createRange();c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(s_ga.Range.START_TO_END,a)},s_Ana=function(a,b){var c={};s_g(a,function(d,e){c[b.call(void 0,d,e,a)]=d});return c};s_D("sy83");
var s_Bna=!1,s_Dk={preload:"yp",filled:"yf",inlined:"yi"},s_Cna=s_sb(s_Dk),s_Dna={loading:"yl",error:"ye"},s_Ena=s_sb(s_Dna),s_Fna={preload:"asyncReset",filled:"asyncFilled",loading:"asyncLoading",error:"asyncError"},s_Gna=function(){};s_f(s_Gna,Error);var s_Ek=function(a){this.element=a;this.type=s_t(a,"asyncType")||"";if(!this.type)throw a=new s_Gna,s_me(a),a;},s_Fk=function(a){var b=s_t(a,"asyncTrigger");if(b){if(a=s_i(b))return new s_Ek(a);a=new s_Gna;s_me(a);throw a;}return new s_Ek(a)};
s_Ek.prototype.getState=function(){var a=s_Ze(this.element);return s_Xa(s_Sa(a,function(a){return s_Cna[a]}),s_hd)};var s_Hna=function(a){a=s_Ze(a.element);return s_Xa(s_Sa(a,function(a){return s_Ena[a]}),s_hd)||""};s_Ek.prototype.setState=function(a){s_Ina(this,a);"filled"==a&&s_g(this.element.querySelectorAll("."+s_Dk.inlined),function(a){s_Ina(new s_Ek(a),"filled")})};
var s_Gk=function(a,b){s_0e(a.element,s_jb(s_Dna));if(""!=b){s_w(a.element,s_Dna[b]);var c=a.getState();s_2g(a.element,s_Fna[b],{state:c,Z7:b})}},s_Ina=function(a,b){s_0e(a.element,s_jb(s_Dk));s_w(a.element,s_Dk[b]);s_Gk(a,"");s_2g(a.element,s_Fna[b],{state:b,Z7:""})},s_Jna=function(a){return(a=s_t(a.element,"asyncContextRequired"))?a.split(","):[]},s_Hk=function(a,b,c,d){this.target=a;this.trigger=c;c=b=s_rb(b);var e;var f=this.trigger||this.target.element;e=s_Jna(this.target);var g=b;if(e.length){e=
new s_xe(e);for(var g=new s_xe(s_kb(g)),k={};f&&null!=f.parentNode&&!s_Xca(e,g);){var l=s_t(f,"asyncContext");if(l)for(var l=l.split(";"),m=0;m<l.length;++m){var n=l[m].split(":");2==n.length?(n[0]=s_Aa(n[0]),n[1]=s_Aa(n[1]),e.contains(n[0])&&!g.contains(n[0])&&(k[n[0]]=n[1],g.add(n[0]))):s_me(Error("W"),{cxt:l[m]})}f=f.parentNode}e=k}else e={};s_tb(c,e);c=b;e=this.target.element;e.id!=this.target.type&&(c._id=e.id);(e=s_t(this.target.element,"asyncToken"))&&(c._xsrf=e);c._pms=s_sf(google.xjsu,"k").match(/xjs\.(\w+)\./)[1];
this.context=b;this.$=d||{};this.Mr="stateful"==s_t(a.element,"asyncMethod")||s_t(a.element,"asyncToken")?"POST":"GET";this.ka=s_t(a.element,"asyncRclass")||""},s_Ik=function(a,b,c,d){if(s_Kc(a))e=s_Fk(a),a=s_t(a,"asyncTrigger")?a:void 0;else{var e=a;a=c}return new s_Hk(e,b||{},a,d)},s_Kna=function(a,b,c){var d;d=b.getStatus()?Error("vd"):Error("wd");d.details={s:b.getStatus()};c&&(d.details.e=c);0==b.getStatus()&&s_me(d,d.details);a.reject(d)},s_Lna=function(a){var b="POST"==a.Mr?{}:a.context,c=
s_Qe(a.target.element),d=google.getEI(a.target.element),e=a.trigger?s_Qe(a.trigger):void 0,f=a.trigger?google.getLEI(a.trigger):void 0;return("search"==a.ka?s_gna:s_fna)(a.target.type,b,a.$,c,d,e,f)},s_Mna=function(a){if("POST"==a.Mr){var b={},c=s_ana(a.context);c&&(b.async=a.target.type+","+c);var d=[];s_fb(b,function(a,b){d.push(b+"="+a)});return d.join("&")}};
s_Hk.prototype.fetch=function(){var a;a=new s_xe(s_Jna(this.target));var b={};s_tb(b,this.context);s_tb(b,this.$);b=new s_xe(s_kb(b));s_Xca(a,b)?a=!0:(a=s_hfa(a,b).Xc().join(","),s_me(Error("U"),{type:this.target.type,cxt:a}),a=!1);return a?s_Nna(this):s_jf(void 0)};
var s_Nna=function(a){var b=s_lf(),c=s_Lna(a),c=c+(s_kda&&s_bf?s_cf():""),d=a.target.type;s_uk(c,function(a){var c=a.target;if("complete"==a.type)if(c.isSuccess()){a=c.Hm();var e="\n\n";s_Ca(a,e)||(e="\n");a=s_Ra(a.split(e),s_hd);var k=[];a=s_Ra(s_Sa(a,function(a){try{var d=JSON.parse(a),e=d.__err__;if(s_a(e))s_Kna(b,c,e);else return s_Lka(d)}catch(ba){s_Xg("deb")?k.push(ba):(s_Kna(b,c),s_me(ba,{a:"1"}))}}),s_hd);(e=c.getResponseHeader("Version"))&&s_xna(parseInt(e,10));b.resolve(a)}else s_Kna(b,
c);else s_Kna(b,c),s_me(Error("V"),{type:d})},a.Mr,s_Mna(a),void 0,void 0,s_Bna);return b.$},s_Ona=function(){s_g(document.querySelectorAll("."+s_Dk.inlined),function(a){s_Ina(new s_Ek(a),"filled")})},s_Kk=function(a){var b=s_Fk(a);return"preload"!=b.getState()||"loading"==s_Hna(b)?s_B(void 0):s_Jk(a,void 0,void 0,void 0)},s_Jk=function(a,b,c,d,e){if(b instanceof Map){var f=b;b={};f.forEach(function(a,c){b[c]=a})}var g=e?s_Ik(s_Fk(a),b,e):s_Ik(a,b);a=c||1;1!=a&&(d=d?d(g.context):g.context,s_Pna(g.target.element.id,
g.target.type,d,a));s_Gk(g.target,"loading");return s_nf(g.fetch().then(function(a){s_g(a,function(a){a.apply()});g.target.setState("filled")}),function(a){s_Gk(g.target,"error");throw a;})},s_Qna=function(a){var b={};a.forEach(function(a,d){b[d]=a});return b},s_Lk=function(a,b,c){var d;void 0!=c&&(d=s_Qna(c));var e=s_Ik(a,b,void 0,d);s_Gk(e.target,"loading");return s_nf(e.fetch().then(function(a){s_g(a,function(a){(new s_Xj(a.Pl,s__j.Et())).append(a)});e.target.setState("filled")}),function(a){s_Gk(e.target,
"error");throw a;})},s_Mk=function(a,b,c){return s_Ik(a,b,c,void 0).fetch()},s_Ok=function(a){a=s_Ik(a);delete s_Nk[a.target.element.id];s_Rg("async",s_Rna(),!1);s_Bc(a.target.element);s_wha(a.target.element.id);a.target.setState("preload")},s_Sna=function(a,b,c){this.id=a;this.type=b;this.context=c},s_Tna=function(a){if(!a)return null;var b=s_Na(a,",",1);a=b[0];var b=s_vna(b[1]),c=b._id||a;s_ob(b,"_id");return new s_Sna(c,a,b)};
s_Sna.prototype.yb=function(){var a=s_rb(this.context);this.id!=this.type&&(a._id=this.id);return s_nb(a)?this.type:this.type+","+s_ana(a)};s_Sna.prototype.apply=function(){var a=document.getElementById(this.id);if(!a)return!1;if(s_t(a,"asyncDisableReplay"))return!0;s_Jk(a,this.context);return!0};
var s_Una=function(a){a=s_Sa(a.split(";"),s_Tna);a=s_Ra(a,function(a){return null!=a});return s_Ana(a,function(a){return a.id})},s_Rna=function(){var a=s_Sa(s_jb(s_Nk),function(a){return a.yb()});return s_Ra(a,function(a){return null!=a}).join(";")},s_Nk={},s_Vna="",s_Pna=function(a,b,c,d){1!=d&&(c=s_gb(c,function(a,b){return"_id"!=b}),s_Nk[a]=new s_Sna(a,b,c),a=s_Rna(),a!=s_Vna&&(s_Rg("async",a,3==d),s_6j&&s_wna()))},s_Wna=function(a,b){s_Vna=a;if(b)s_Nk=s_Una(a),s_Ra(s_jb(s_Nk),function(a){return!a.apply()});
else{a=s_Una(a);for(var c in s_Nk)if(!(c in a)){var d=document.getElementById(c);d&&s_Ok(d)}for(c in a)b=a[c],d=s_Nk[c],d&&s_fg(d.context,b.context)||(d=document.getElementById(c))&&s_Jk(d,b.context)}};s_Ge("async",{init:function(a){a.slm&&(s_lna=a.slm);s_Ng("async",s_Wna);s_dh("async",{u:function(a){s_Jk(a)},uo:function(a){s_Kk(a)},r:s_Ok});s_Ona()}});

s_C("sy83");s_E();
}catch(e){_DumpException(e)}
try{
s_D("em16");
s_C("em16");s_E();
}catch(e){_DumpException(e)}
try{
s_D("async");
s_C("async");s_E();
}catch(e){_DumpException(e)}
try{
s_D("erh");var s_Dqb=function(){var a="/webhp?ssrp=1",b=s_Yg("hl");b&&(a+="&hl="+b);s_6e(a)};s_Fe("erh",{init:function(){s_dh("erh",{hc:s_Dqb})}});
s_C("erh");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy85");var s_Pk=null,s_Yna=!0,s_Qk=s_b;
s_C("sy85");s_E();
}catch(e){_DumpException(e)}
try{
var s_Zna=function(){var a=s_i("fbar"),b=s_i("fuser")||s_i("fsr"),c=s_i("fsl");a&&b&&c&&(a=s_l("fbar",a),s_x(a,"fmulti"),32>a.clientWidth-c.offsetWidth-b.offsetWidth-30-34&&s_w(a,"fmulti"))},s__na=!1,s_0na=!1,s_1na=0,s_2na=function(){var a=s_Pk=s_Pk||s_i("fbarcnt"),b=s_i("fbar");if(b&&a&&s_Nd(a)&&(s__na||!s_0na||s_1na!=window.innerWidth)){s_1na=window.innerWidth;s_q(a,{height:"auto"});s_q(b,{bottom:"",position:""});s_Zna();if(s_i("dbg_"))s_q(b,{position:"static"});else{var c=window.innerHeight||Math.max(document.documentElement.clientHeight, document.body.scrollHeight),d=s_Ad(a).y,c=c-d;c>b.offsetHeight&&(s_q(a,{height:c+"px"}),s_q(b,{bottom:"0",position:"absolute"}))}s_q(a,{visibility:"visible"})}};s_D("foot");
var s_3na=null,s_Rk=null,s_Sk=null,s_5na=function(){if(s_Nd(s_Rk))s_Sk.setAttribute("aria-expanded","false"),s_4na();else{s_Sk.setAttribute("aria-expanded","true");var a=s_r(s_Rk),b=-20;if(s_pf())c=s_r(s_Sk),0>s_Ad(s_Sk).x+c.width-a.width-b&&(b=s_Vd(s_Sk),b=c.width-a.width+b.left+b.right),s_Rk.style.right=b+"px";else{if(s_Ad(s_Sk).x+a.width+b>s_sc().width)var c=s_r(s_Sk),b=s_Vd(s_Sk),b=c.width-a.width+b.left+b.right;s_Rk.style.left=b+"px"}s_s(s_Rk,!0);s_He(document.body,"click",s_4na)}},s_4na=function(a){a&&
a.target==s_Sk||s_s(s_Rk,!1);s_Ie(document.body,"click",s_4na)},s_6na=function(a){s_3na&&s_s(s_3na,!a)};
s_Fe("foot",{init:function(a){s_Rk=s_i("fsett");s_Sk=s_i("fsettl");s_Rk&&s_Sk&&s_dh("foot",{cst:s_5na});var b=s_i("fbar");b&&s_s(b,!0);s_3na=s_i("footcnt");s_6na(!1);var b=a.po,c=a.qe,d=a.pf;s_Pk=s_i("fbarcnt");s__na=!!c;s_Yna=null!=s_Pk&&(void 0===d||d);s_0na=!!b;s_Qk=s_Yna?s_ff(null,s_2na,!1):s_Zna;s_Qk();s_He(window,"resize",s_Qk);s_Xe(165,s_Qk);void 0!==a.dv&&""!==a.dv&&s_Zf.set("DV",a.dv,600)},dispose:function(){s_fh("foot",["cst"])}});s_Xe(37,s_6na);s_Xe(155,s_d(s_6na,!0));

s_C("foot");s_E();
}catch(e){_DumpException(e)}
try{
s_D("fpe");var s_sId,s_tId=!1,s_o5=function(a){s_h.call(this);var b=a||!1;a=!!(s_4j()&&window.gbar&&gbar.elc&&gbar.elr);this.qa=b&&!a;this.ma=[];s_tId||(a&&gbar.elc(s_c(function(){b&&s_uId(gbar.elr().mo);s_u(71)},this)),s_tId=!0);this.qa&&(this.$=s_ff(null,s_c(this.Ea,this),!0),s_p(window,"resize",this.$,!1,this),this.$());(a=s_i("tbbcc"))&&this.ma.push(a);this.ha();s_p(window,"scroll",this.ha,!1,this)};s_f(s_o5,s_h);
s_o5.prototype.Ha=function(){this.ma=[];this.qa&&s_9c(window,"resize",this.$,!1,this);s_9c(window,"scroll",this.ha,!1,this)};var s_uId=function(a){var b=s_i("cnt"),c=s_i("searchform");b&&(s_y(b,"big","lg"==a),s_y(b,"mdm","md"==a));c&&(s_y(c,"big","lg"==a),s_y(c,"mdm","md"==a))};s_o5.prototype.Ea=function(){s_uId(1250<=document.body.offsetWidth?"lg":"sm")};s_o5.prototype.$=null;
s_o5.prototype.ha=function(){var a=window.pageXOffset||document.body.scrollLeft||document.documentElement.scrollLeft,b=s_pf(),c=b?"marginRight":"marginLeft",d=b?"right":"left";b&&(a=Math.abs(a));for(var b=0,e;e=this.ma[b];b++)"fixed"==s_wd(e)&&("tbbcc"==e.id?e.style[c]=-a+"px":e.style[d]=-a+"px")};s_Fe("fpe",{init:function(a){s_sId=new s_o5(a.js)},dispose:function(){s_sId&&(s_sId.dispose(),s_sId=null)}});

s_C("fpe");s_E();
}catch(e){_DumpException(e)}
try{
s_D("ipv6");var s_Tk=null,s_7na=function(a){s_sa("google.v6t",s_e());s_sa("google.v6s",0);s_Tk=new Image;s_sa("google.v6",s_Tk);s_Tk.onload=s_Tk.onerror=function(){s_sa("google.v6s",1)};s_Tk.src=a+"&rndm="+Math.random()};s_Ge("ipv6",{init:function(a){a.url&&s_7na(a.url)},dispose:function(){s_Tk=null}});

s_C("ipv6");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy152");
s_C("sy152");s_E();
}catch(e){_DumpException(e)}
try{
var s_pxa=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e,f=null;0<=d?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?s_Aa(f):"")}}},s_qxa=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^s_e()).toString(36)};s_D("sy185");
var s_bq=function(a,b){this.ka=this.Da=this.qa="";this.Ea=null;this.Wa=this.ma="";this.Ca=!1;var c;a instanceof s_bq?(this.Ca=s_a(b)?b:a.Ca,s_cq(this,a.qa),this.Da=a.Da,s_dq(this,a.ka),s_eq(this,a.Ea),s_fq(this,a.ma),s_gq(this,a.ha.clone()),s_hq(this,a.Wa)):a&&(c=String(a).match(s_ae))?(this.Ca=!!b,s_cq(this,c[1]||"",!0),this.Da=s_iq(c[2]||""),s_dq(this,c[3]||"",!0),s_eq(this,c[4]),s_fq(this,c[5]||"",!0),s_gq(this,c[6]||"",!0),s_hq(this,c[7]||"",!0)):(this.Ca=!!b,this.ha=new s_jq(null,0,this.Ca))};
s_bq.prototype.toString=function(){var a=[],b=this.qa;b&&a.push(s_kq(b,s_rxa,!0),":");var c=this.ka;if(c||"file"==b)a.push("//"),(b=this.Da)&&a.push(s_kq(b,s_rxa,!0),"@"),a.push(s_za(c).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Ea,null!=c&&a.push(":",String(c));if(c=this.ma)this.ka&&"/"!=c.charAt(0)&&a.push("/"),a.push(s_kq(c,"/"==c.charAt(0)?s_sxa:s_txa,!0));(c=this.ha.toString())&&a.push("?",c);(c=this.Wa)&&a.push("#",s_kq(c,s_uxa));return a.join("")};
s_bq.prototype.resolve=function(a){var b=this.clone(),c=!!a.qa;c?s_cq(b,a.qa):c=!!a.Da;c?b.Da=a.Da:c=!!a.ka;c?s_dq(b,a.ka):c=null!=a.Ea;var d=a.ma;if(c)s_eq(b,a.Ea);else if(c=!!a.ma){if("/"!=d.charAt(0))if(this.ka&&!this.ma)d="/"+d;else{var e=b.ma.lastIndexOf("/");-1!=e&&(d=b.ma.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(s_Ca(e,"./")||s_Ca(e,"/.")){for(var d=s_ua(e,"/"),e=e.split("/"),f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&f.push(""):".."==k?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?s_fq(b,d):c=""!==a.ha.toString();c?s_gq(b,a.ha.clone()):c=!!a.Wa;c&&s_hq(b,a.Wa);return b};s_bq.prototype.clone=function(){return new s_bq(this)};
var s_cq=function(a,b,c){a.qa=c?s_iq(b,!0):b;a.qa&&(a.qa=a.qa.replace(/:$/,""));return a},s_dq=function(a,b,c){a.ka=c?s_iq(b,!0):b;return a},s_eq=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("sa`"+b);a.Ea=b}else a.Ea=null},s_fq=function(a,b,c){a.ma=c?s_iq(b,!0):b;return a},s_gq=function(a,b,c){b instanceof s_jq?(a.ha=b,s_vxa(a.ha,a.Ca)):(c||(b=s_kq(b,s_wxa)),a.ha=new s_jq(b,0,a.Ca));return a};s_bq.prototype.getQuery=function(){return this.ha.toString()};
s_bq.prototype.$=function(a,b){this.ha.set(a,b);return this};
var s_lq=function(a,b,c){s_la(c)||(c=[String(c)]);s_xxa(a.ha,b,c);return a},s_mq=function(a,b){return a.ha.get(b)},s_hq=function(a,b,c){a.Wa=c?s_iq(b):b;return a},s_nq=function(a,b){return a instanceof s_bq?a.clone():new s_bq(a,b)},s_yxa=function(a,b,c,d,e,f){var g=new s_bq(null,void 0);a&&s_cq(g,a);b&&s_dq(g,b);c&&s_eq(g,c);d&&s_fq(g,d);e&&s_gq(g,e);f&&s_hq(g,f);return g},s_iq=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},s_kq=function(a,b,c){return s_na(a)?
(a=encodeURI(a).replace(b,s_zxa),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},s_zxa=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},s_rxa=/[#\/\?@]/g,s_txa=/[\#\?:]/g,s_sxa=/[\#\?]/g,s_wxa=/[\#\?@]/g,s_uxa=/#/g,s_jq=function(a,b,c){this.ka=this.$=null;this.ha=a||null;this.ma=!!c},s_oq=function(a){a.$||(a.$=new s_se,a.ka=0,a.ha&&s_pxa(a.ha,function(b,c){a.add(s_Aa(b),c)}))},s_Axa=function(a){var b=s_Tca(a);if("undefined"==typeof b)throw Error("Bd");var c=
new s_jq(null,0,void 0);a=s_we(a);for(var d=0;d<b.length;d++){var e=b[d],f=a[d];s_la(f)?s_xxa(c,e,f):c.add(e,f)}return c};s_=s_jq.prototype;s_.ze=function(){s_oq(this);return this.ka};s_.add=function(a,b){s_oq(this);this.ha=null;a=s_pq(this,a);var c=this.$.get(a);c||this.$.set(a,c=[]);c.push(b);this.ka+=1;return this};s_.remove=function(a){s_oq(this);a=s_pq(this,a);return s_ve(this.$,a)?(this.ha=null,this.ka-=this.$.get(a).length,this.$.remove(a)):!1};
s_.clear=function(){this.$=this.ha=null;this.ka=0};s_.isEmpty=function(){s_oq(this);return 0==this.ka};var s_Bxa=function(a,b){s_oq(a);b=s_pq(a,b);return s_ve(a.$,b)};s_=s_jq.prototype;s_.Us=function(a){var b=this.Xc();return s_Ya(b,a)};s_.Pf=function(){s_oq(this);for(var a=this.$.Xc(),b=this.$.Pf(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
s_.Xc=function(a){s_oq(this);var b=[];if(s_na(a))s_Bxa(this,a)&&(b=s_3a(b,this.$.get(s_pq(this,a))));else{a=this.$.Xc();for(var c=0;c<a.length;c++)b=s_3a(b,a[c])}return b};s_.set=function(a,b){s_oq(this);this.ha=null;a=s_pq(this,a);s_Bxa(this,a)&&(this.ka-=this.$.get(a).length);this.$.set(a,[b]);this.ka+=1;return this};s_.get=function(a,b){a=a?this.Xc(a):[];return 0<a.length?String(a[0]):b};var s_xxa=function(a,b,c){a.remove(b);0<c.length&&(a.ha=null,a.$.set(s_pq(a,b),s_4a(c)),a.ka+=c.length)};
s_jq.prototype.toString=function(){if(this.ha)return this.ha;if(!this.$)return"";for(var a=[],b=this.$.Pf(),c=0;c<b.length;c++)for(var d=b[c],e=s_za(d),d=this.Xc(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+s_za(d[f]));a.push(g)}return this.ha=a.join("&")};s_jq.prototype.clone=function(){var a=new s_jq;a.ha=this.ha;this.$&&(a.$=this.$.clone(),a.ka=this.ka);return a};
var s_pq=function(a,b){b=String(b);a.ma&&(b=b.toLowerCase());return b},s_vxa=function(a,b){b&&!a.ma&&(s_oq(a),a.ha=null,a.$.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),s_xxa(this,c,a))},a));a.ma=b};s_jq.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)s_Uca(arguments[b],function(a,b){this.add(b,a)},this)};

s_C("sy185");s_E();
}catch(e){_DumpException(e)}
try{
s_D("lu");var s_iXc=["luibli","luibbri"],s_jXc={},s_ZY=-1,s_kXc=null,s_lXc=function(a,b,c){a=a.cloneNode(!0);var d,e;b.hasAttribute("data-mh")&&(d=b.getAttribute("data-mh"));b.hasAttribute("data-mw")?e=b.getAttribute("data-mw"):e=88*c-16;var f;"IMG"==a.tagName?f=a:f=a.getElementsByTagName("IMG")[0];f.id="";f.width=e;void 0!==d&&(f.height=d);f.onload=function(){f.style.display="block";delete f.onload};f.style.display="none";c=f.src.split("&")[0]+"&w="+e;void 0!==d&&(c+="&h="+d);f.src=c;null!=f.parentNode&&(f.parentNode.style.width=
e+"px",void 0!==d&&(f.parentNode.style.height=d+"px"));b.appendChild(a)},s_mXc=function(a){if(!a)return null;var b,c=0,d;for(d in a)if(d=Number(d),0<a[d].offsetHeight){b=a[d];c=d;break}if(!b)return null;if(!b.firstChild){var e;for(d in a)if(d=Number(d),a[d].firstChild){e=a[d];break}s_lXc(e.firstChild,b,c)}return{element:b,wFa:c}},s_pXc=function(){for(var a=s_nXc(),b=!1,c=0;c<s_iXc.length;c++)for(var d=s_k(s_iXc[c]),e=0;e<d.length;e++)s_oXc(d[e])&&(b=!0);return a||b},s_nXc=function(){var a=s_i("rhs_block");
if(!a||0==a.offsetHeight)return!1;a:{for(var b={},c=3;5>=c;c++)if(b[c]=a.querySelector(".rhsmap"+c+"col"),b[c])b[c].column_count=c;else{a=null;break a}a=b}b=s_mXc(a);if(!b)return!1;a=b.wFa;if(s_ZY==a&&s_jXc[s_ZY])return!0;b=b.element.getElementsByTagName("IMG")[0];b.id||(s_i("lu_map").id="",b.id="lu_map");s_jXc[a]||(s_jXc[a]=!0);s_ZY=a;return!0},s_oXc=function(a){for(var b=[],c,d="1"==a.getAttribute("data-crop"),e="1"==a.getAttribute("data-contain"),f=3;5>=f;f++){var g=a.querySelector(".luib-"+f);
if(!g)return!1;g=g.querySelector(".thumb");if(!g)return!1;b.push(g);0<g.offsetHeight&&(c=g)}if(!c)return!1;var k=parseInt(c.style.width,10),g=parseInt(c.style.height,10);if((f=c.querySelector("img"))&&f.src)return!0;for(var l,m,f=0;f<b.length;f++){var n=b[f].querySelector("img");if(n&&n.src){l=s_m("DIV");l.innerHTML=b[f].innerHTML;e&&(l.style.backgroundColor=b[f].style.backgroundColor);m=n;break}}if(!m)return!1;b=l.querySelector("img");d||e||(b.width=k,b.height=g,m=s_nq(m.src),m.$("w",parseInt(k,
10)),m.$("h",parseInt(g,10)),b.src=m.toString());c.innerHTML=l.innerHTML;d&&(b=c.querySelector("img"),d=(k-b.width)/2+"px",s_Pd(a)?b.style.right=d:b.style.left=d,b.style.top=(g-b.height)/2+"px");e&&(b=c.querySelector("img"),c.style.backgroundColor=l.style.backgroundColor,l=Math.min(c.offsetHeight/b.height,c.offsetWidth/b.width),e=b.width*l,l*=b.height,b.width=e,b.height=l,b.style.top=(c.offsetHeight-l)/2+"px",d=(c.offsetWidth-e)/2+"px",s_Pd(a)?b.style.right=d:b.style.left=d);return!0}; s_Fe("lu",{init:function(){"webhp"!=google.sn&&s_i("lu_map")&&(s_pXc()?(s_kXc=s_ff(null,s_pXc,!0),s_Xe(60,s_kXc)):(s_ZY=3,s_jXc[s_ZY]=!0))},dispose:function(){s_kXc&&(s_Ye(60,s_kXc),s_kXc=null);s_jXc={};s_ZY=-1}});

s_C("lu");s_E();
}catch(e){_DumpException(e)}
try{
var s_AId={};s_D("m");var s_r5=null;var s_BId,s_CId,s_DId,s_EId,s_FId,s_s5,s_GId={},s_t5=null,s_u5=null,s_v5=[],s_IId=function(){s_r5.ab.on&&(s_Xe(41,s_HId),s_Xe(37,function(a){a&&(a=s_i("appbar"))&&(a.style.visibility="hidden")}),s_i("pocs"))},s_JId=function(){return s_i("sftab")||s_i("lst-ib")},s_KId=function(){var a=s_JId();a&&s_w(a,"lst-d-f")},s_LId=function(){var a=s_JId();a&&s_x(a,"lst-d-f")},s_MId=function(a){this.element=a;this.$=[];this.ka=null;"ab_opt"==this.element.id&&0==this.element.childNodes.length&&gbar.aomc(this.element);
a=s_k("ab_dropdownitem",this.element);for(var b=0,c;c=a[b];b++)s_v(c,"disabled")||this.$.push(c)},s_OId=function(a){var b=s_t5;s_NId(b,null==b.ka?a?0:b.$.length-1:(b.ka+(a?1:b.$.length-1))%b.$.length)},s_NId=function(a,b){var c=a.$[b];c&&(s_PId(a),s_w(c,"selected"),c.setAttribute("aria-selected","true"),c=c.querySelector("a, .action-menu-button")||c,c.setAttribute("tabindex","0"),c.focus(),a.ka=b)},s_PId=function(a){var b=a.$[a.ka];b&&(s_x(b,"selected"),b.setAttribute("aria-selected","false"),(b.querySelector("a, .action-menu-button")||
b).setAttribute("tabindex","-1"),a.element.focus(),a.ka=null)};s_MId.prototype.kd=function(a){for(var b=0,c;c=this.$[b];b++)if(a==c){b!=this.ka&&s_NId(this,b);break}};
var s_RId=function(a){var b=(a=s_Tc(a,"ab_button"))&&s_u5!=a;s_t5&&s_w5();a&&b&&s_QId(a)},s_SId=function(a){google.ac&&google.ac.cc&&google.ac.cc();s_6e(a.href);return!0},s_TId=function(a,b,c){32==c.keyCode&&s_6e(a.href)},s_UId=function(a){s_s(s_i("ufp"),"block");s_RId(a)},s_QId=function(a,b){var c;c=s_ra(a);if(void 0==s_GId[c]){var d;d=s_Tc(a,"ab_ctl");var e=null;d&&(d=s_l("ab_dropdown",d))&&(e=new s_MId(d));s_GId[c]=e}if(c=s_GId[c])s_w(a,"selected"),a.setAttribute("aria-expanded","true"),s_u5=a,
c.element.style.visibility="inherit",s_t5=c,c=a.id.indexOf("am-b"),a.id&&-1!=c&&(c=s_Lc(a))&&s_v(c,"action-menu")&&(c=s_l("action-menu-panel",c))&&s_z(a,[c],[],"","&id="+a.id),s_He(document.body,"click",s_w5),s_He(document.body,"keydown",s_VId),b&&s_OId(!0)},s_w5=function(a){s_t5&&((a=a||window.event)&&"click"==a.type&&s_Tc(s_df(a),"ab_button")&&(s_ef(a),a.preventDefault?a.preventDefault():a.returnValue=!1),s_Ie(document.body,"click",s_w5),s_Ie(document.body,"keydown",s_VId),s_PId(s_t5),s_t5.element.style.visibility=
"hidden",s_t5=null);s_u5&&(s_x(s_u5,"selected"),s_u5.setAttribute("aria-expanded","false"),s_u5=null)},s_VId=function(a){27==a.keyCode&&s_w5()},s_WId=function(a,b,c){if(9==c.keyCode)s_w5();else if(27==c.keyCode){if(s_t5)return s_w5(),s_x5(c)}else{if(38==c.keyCode||40==c.keyCode)return s_t5?s_OId(40==c.keyCode):s_QId(a,!0),s_x5(c);if(37==c.keyCode||39==c.keyCode)return s_x5(c)}return!0},s_XId=function(a,b,c){s_t5&&((a=s_Tc(s_df(c),"ab_dropdownitem"))?s_t5.kd(a):s_PId(s_t5))},s_YId=function(){s_t5&&
s_PId(s_t5)},s_ZId=function(a,b,c){if(s_t5)if(9==c.keyCode)s_w5();else{if(27==c.keyCode)return a=s_u5,s_w5(),a.focus(),s_x5(c);if(38==c.keyCode)return s_OId(!1),s_x5(c);if(40==c.keyCode)return s_OId(!0),s_x5(c);if(32==c.keyCode||37==c.keyCode||39==c.keyCode)return s_x5(c)}return!0},s_x5=function(a){s_ef(a);a.preventDefault&&a.preventDefault();return a.returnValue=!1},s__Id=function(a){return s_yb()?(37!=a.keyCode&&38!=a.keyCode&&39!=a.keyCode&&40!=a.keyCode||s_x5(a),!1):!0},s_HId=function(a){var b=
s_i("rcnt"),c=s_5j();if(c&&b){var d=parseInt(s_td(c,"top"),10),e=s_JId(),e=e?e.offsetHeight:c.offsetHeight,b=s_Fd(b);if(a!=s_BId||d!=s_CId||e!=s_DId||b!=s_EId){s_BId=a;s_CId=d;s_DId=e;s_EId=b;var d=0,f;if(f=a)f=!s_AId.isch;f&&(c=s_Fd(c)+e,d=Math.max(0,a+7-b+c));s_FId=d}(a=s_i("center_col"))&&a.style.paddingTop!=s_FId+"px"&&(a.style.paddingTop=s_FId+"px")}return!1},s_0Id=function(){var a=s_i("bbar");a&&s_s(a,!1)},s_1Id=function(a){s_s5&&s_s5.remove("bbh");s_6e(a.href)};
var s_2Id=!1;
s_Fe("m",{init:function(a){s_r5=a;s_2Id||s_IId();s_2Id=!0;s_JId()&&(a=s_i("lst-ib"),s_He(a,"focus",s_KId),s_He(a,"blur",s_LId),a==s_Uc(document)&&s_KId());s_s5=s_7f("local","abar");s_v5=[];(a=s_i("abar_ps_on"))&&s_v5.push(new s_q5(a,s_v(a,"disabled")?s_r5.msgs.sPersD:s_r5.msgs.sPers));(a=s_i("abar_ps_off"))&&s_v5.push(new s_q5(a,s_v(a,"disabled")?s_r5.msgs.hPersD:s_r5.msgs.hPers));a=s_s5?s_s5.get("bbh"):"";var b=document.getElementById("safesearch");"1"==a||b&&!b.getAttribute("data-safesearch-on")||!(a=
document.getElementById("bbar"))||(s_q(a,"visibility","hidden"),s_s(a,!0),b=s_r(a),s_q(a,"margin-left",-Math.floor(b.width/2)+"px"),s_q(a,"visibility","visible"),s_s5&&s_s5.set("bbh",1));s_dh("m",{cc:s_SId,hbke:s_WId,hdke:s_ZId,hdhne:s_XId,hdhue:s_YId,go:s_TId,mskpe:s__Id,tdd:s_RId,tei:s_UId,hbb:s_0Id,cbbl:s_1Id},!0);s_dh("ab",{cc:s_SId,hbke:s_WId,hdke:s_ZId,hdhne:s_XId,hdhue:s_YId,go:s_TId,mskpe:s__Id,tdd:s_RId,tei:s_UId,hbb:s_0Id,cbbl:s_1Id},!0)},dispose:function(){if(s_JId()){var a=s_i("lst-ib"); s_Ie(a,"focus",s_KId);s_Ie(a,"blur",s_LId)}s_t5&&s_w5();s_GId={};for(a=0;a<s_v5.length;a++)s_v5[a].destroy();s_v5=[];s_fh("ab","cc hbke hdke hdhne hdhue go mskpe tdd tei tne".split(" "))}});

s_C("m");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sf");s_Fe("sf",{init:function(){s_dh("sf",{chk:function(a){a.checked=!0},lck:function(a){a.form.q.value?a.checked=!0:s_ie().href="/doodles/"},tia:function(a,b){a=s_m("SCRIPT",{src:b.js});s_Xd(a)}})}});
s_C("sf");s_E();
}catch(e){_DumpException(e)}
try{
var s_3ra=!1;s_D("vm");s_Fe("vm",{init:function(a){s_3ra?"bv"in a&&(a=a.bv,s_af=a>s_$e?1:a<s_$e?2:0,s_bf=!0):(s_3ra=!0,"bv"in a&&(s_$e=a.bv),s_af=0,"d"in a&&(s_hda=a.d),"tc"in a&&(s_ida=a.tc),"te"in a&&(s_jda=a.te),"ts"in a&&(s_kda=a.ts),"tk"in a&&(s_lda=a.tk))}});
s_C("vm");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy94");var s_eoa=function(a){this.Aa=a;this.Aa._wect=this;this.ka={};this.$={};this.ha={}};s_eoa.prototype.Dd=null;var s_foa=function(a){a._wect||new s_eoa(a);return a._wect};s_eoa.prototype.ma=function(a,b){void 0==this.ka[a]&&(this.ka[a]=0);this.ka[a]++;for(var c=this.$[a],d=c.length,e,f=0;f<d;f++)try{c[f](b)}catch(g){e=e||g}this.ka[a]--;if(e)throw e;};
var s_goa=function(a,b){a.ha[b]||(a.ha[b]=s_c(a.ma,a,b));return a.ha[b]},s_hoa=function(a,b){return a+":"+(b?"capture":"bubble")},s_ioa=function(a,b,c,d){d=!!d;var e=s_hoa(b,d);a.$[e]||(a.$[e]=[],a.Aa.addEventListener(b,s_goa(a,e),d));a.$[e].push(c)},s_joa=function(a,b,c,d){d=!!d;var e=s_hoa(b,d);a.$[e]&&(a.ka[e]&&(a.$[e]=a.$[e].slice(0)),c=a.$[e].indexOf(c),-1!=c&&a.$[e].splice(c,1),0==a.$[e].length&&(a.$[e]=void 0,a.Aa.removeEventListener(b,s_goa(a,e),d)))};
var s_6k=function(a,b,c,d){s_joa(s_foa(a),b,c,d)},s_7k=function(a,b,c,d,e){var f=s_foa(a);s_ioa(f,b,c,d);e&&s_koa(a,function(){s_ioa(f,b,c,d)},function(){s_joa(f,b,c,d)})},s_koa=function(a,b,c){a.addEventListener("DOMFocusIn",function(a){a.target&&"TEXTAREA"==a.target.tagName&&b()},!1);a.addEventListener("DOMFocusOut",function(a){a.target&&"TEXTAREA"==a.target.tagName&&c()},!1)};
var s_loa=/iPhone|iPod|iPad/,s_8k=function(){return s_Ca(navigator.userAgent,"Android")},s_moa=/Mac OS X.+Silk\//;var s_9k=s_loa.test(navigator.userAgent)||s_8k()||s_moa.test(navigator.userAgent),s_$k=window.navigator.msPointerEnabled,s_al=s_9k?"touchstart":s_$k?"MSPointerDown":"mousedown",s_noa=s_9k?"touchmove":s_$k?"MSPointerMove":"mousemove",s_bl=s_9k?"touchend":s_$k?"MSPointerUp":"mouseup",s_ooa=s_$k?"MSPointerCancel":"touchcancel",s_poa=function(a,b,c,d,e,f,g){s_9k||s_$k||(b=s_cl(b),c=s_cl(c),d=s_cl(d));f=!!f;s_7k(a,s_al,b,f,g);s_7k(a,s_noa,c,f,g);s_7k(a,s_bl,d,f,g);s_7k(a,s_ooa,e,f,g)},s_cl=function(a){return function(b){b.touches= [];b.targetTouches=[];b.changedTouches=[];b.type!=s_bl&&(b.touches[0]=b,b.targetTouches[0]=b);b.changedTouches[0]=b;a(b)}},s_dl=function(a){return a.touches||[a]},s_el=function(a){return(s_$k?[a]:a.changedTouches)||[]};

s_C("sy94");s_E();
}catch(e){_DumpException(e)}
try{
var s_xoa=/Chrome\/([0-9.]+)/,s_yoa=function(){return s_Ca(navigator.userAgent,"Chrome/")},s_zoa=/OS (\d+)_(\d+)(?:_(\d+))?/,s_Aoa=function(a,b,c,d){return a<<21|b<<14|c<<7|d},s_Boa=function(){var a=s_zoa.exec(navigator.userAgent)||[];a.shift();return s_Aoa.apply(null,a)},s_Coa=function(a){var b;if(b=s_8k()&&s_yoa())b=s_xoa.exec(navigator.userAgent),b=18==+(b?b[1]:"").split(".")[0];return b?new s_ec(a.clientX,a.pageY-window.scrollY):new s_ec(a.clientX,a.clientY)};s_D("sy95");
var s_hl,s_Doa,s_Eoa,s_Foa,s_Goa=function(a){if(!(2500<s_e()-s_Doa)){var b=s_Coa(a);if(!(1>b.x&&1>b.y)){for(var c=0;c<s_hl.length;c+=2)if(25>Math.abs(b.x-s_hl[c])&&25>Math.abs(b.y-s_hl[c+1])){s_hl.splice(c,c+2);return}a.stopPropagation();a.preventDefault();(a=s_Eoa)&&a()}}},s_Hoa=function(a){var b=s_Coa(s_dl(a)[0]);s_hl.push(b.x,b.y);window.setTimeout(function(){for(var a=b.x,d=b.y,e=0;e<s_hl.length;e+=2)if(s_hl[e]==a&&s_hl[e+1]==d){s_hl.splice(e,e+2);break}s_Eoa=void 0},2500)},s_Ioa=function(){s_a(s_Foa)||
(s_Foa=s_Boa()>=s_Aoa(6)||!0);return s_Foa},s_il=function(a,b,c){s_Eoa=c;s_hl||(document.addEventListener("click",s_Goa,!0),c=s_Hoa,s_9k||s_$k||(c=s_cl(c)),s_7k(document,s_al,c,!0,!0),s_hl=[]);s_Doa=s_e();for(c=0;c<s_hl.length;c+=2)if(25>Math.abs(a-s_hl[c])&&25>Math.abs(b-s_hl[c+1])){s_hl.splice(c,c+2);break}};

s_C("sy95");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy97");var s_Joa=function(){this.ka=[];this.$=[]},s_Koa=function(a,b,c,d){a.ka.length=a.$.length=0;a.ka.push(b,d);a.$.push(c,d)},s_Noa=function(a,b,c,d){var e=a.ka[a.ka.length-2]-b,f=a.$[a.$.length-2]-c,g=a.ka,k=a.ha;k&&e&&2<g.length&&0<k^0<e&&g.splice(0,g.length-2);g=a.$;(k=a.ma)&&f&&2<g.length&&0<k^0<f&&g.splice(0,g.length-2);s_Loa(a.ka,d);s_Loa(a.$,d);a.ka.push(b,d);a.$.push(c,d);a.ha=e;a.ma=f;return s_Moa(a,b,c,d)},s_Loa=function(a,b){for(;a.length&&250<b-a[1]||10<a.length;)a.splice(0,2)},s_Ooa=function(a,
b,c,d){if(s_a(b)&&s_a(c)&&d)return s_Loa(a.ka,d),s_Loa(a.$,d),s_Moa(a,b,c,d)},s_Moa=function(a,b,c,d){b=a.ka.length?(b-a.ka[0])/(d-a.ka[1]):0;c=a.$.length?(c-a.$[0])/(d-a.$[1]):0;b=s_Poa(a,b);c=s_Poa(a,c);return new s_ec(b,c)},s_Poa=function(a,b){var c=Math.abs(b);5<c&&(c=6>a.$.length?1:5);return c*(0>b?-1:1)};

s_C("sy97");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy99");var s_ipa=s_Nb?"-ms-":s_Pb?"-moz-":s_Mb?0>s_Ha(s_Wb,"15.0")?"-o-":"-webkit-":"-webkit-",s_jpa=s_Nb?"ms":s_Pb?"Moz":s_Mb?0>s_Ha(s_Wb,"15.0")?"O":"webkit":"webkit",s_Pl=s_ipa+"transform",s_Ql=s_jpa+"Transform",s_kpa=s_jpa+"Transition",s_Rl=function(a){a=document.defaultView.getComputedStyle(a,null)[s_Ql];return"undefined"!=typeof WebKitCSSMatrix?new WebKitCSSMatrix(a):"undefined"!=typeof MSCSSMatrix?new MSCSSMatrix(a):"undefined"!=typeof CSSMatrix?new CSSMatrix(a):{}};

s_C("sy99");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy90");var s_El=function(a,b,c){this.x=s_a(a)?a:0;this.y=s_a(b)?b:0;this.z=s_a(c)?c:0};s_El.prototype.clone=function(){return new s_El(this.x,this.y,this.z)};s_El.prototype.Oa=function(){return[this.x,this.y,this.z]};
s_C("sy90");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy92");var s_Fl=function(a){return(a=a.exec(s_db))?a[1]:""},s_2oa=function(){if(s_bda)return s_Fl(/Firefox\/([0-9.]+)/);if(s_Nb||s_Ob||s_Mb)return s_Wb;if(s_dda)return s_Fl(/Chrome\/([0-9.]+)/);if(s_eda&&!s_Ib())return s_Fl(/Version\/([0-9.]+)/);if(s_Je||s_Ke){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(s_db);if(a)return a[1]+"."+a[2]}else if(s_cda)return(a=s_Fl(/Android\s+([0-9.]+)/))?a:s_Fl(/Version\/([0-9.]+)/);return""}();

s_C("sy92");s_E();
}catch(e){_DumpException(e)}
try{
var s_$oa=0,s_Il=function(a){return s_$k?a.pointerId:a.identifier},s_Jl=function(a,b,c,d){var e=document.createEvent("HTMLEvents");e.initEvent(b,!0,!0);e.sender=c;e.Ig=d;a.dispatchEvent(e)},s_Kl=function(a){return a+"_"+s_$oa++};s_D("sy96");var s_Ll=function(a,b,c){this.Db=a;this.rb=b;this.ha=c;this.ka=[];this.Ea=[];this.Da=[];this.Ga=[];this.qa=[];this.Wa=[]};s_Ll.prototype.$=0;var s_apa=function(a,b){var c;b=s_el(b);for(var d=b.length,e=0;e<a.$;e++){a.Ea[e]=void 0;for(var f=0;f<d;f++)if(a.ka[e]==s_Il(b[f])){a.Ea[e]=b[f];c=!0;break}}return c};
s_Ll.prototype.iG=function(a){if(!this.Ca&&this.$!=this.ha){for(var b=s_el(a),c=Math.min(b.length,this.ha-this.$),d=0;d<c;d++){var e=b[d];this.ka[this.$]=s_Il(e);this.qa[this.$]=e.clientX;this.Wa[this.$]=e.clientY;this.$++}s_apa(this,a);if(this.$==this.ha)for(d=0;d<this.ha;d++)this.Da[d]=this.Ga[d]=0;this.nb(a)}};
s_Ll.prototype.OW=function(a){if(!this.Ca&&this.$==this.ha&&s_apa(this,a))if(this.ma)this.Ma(a);else{for(var b,c=0;c<this.ha;c++){var d=this.Ea[c];if(d){var e=this.ka[c],f=this.rb[e]-d.clientY;this.Da[c]+=Math.abs(this.Db[e]-d.clientX);this.Ga[c]+=Math.abs(f);b=b||2<this.Da[c]||2<this.Ga[c]}}if(b){for(c=0;c<this.ha;c++)this.qa[c]=s_bpa(this,c),this.Wa[c]=s_cpa(this,c);(this.ma=this.Mc(a))?this.Ma(a):this.reset()}}};s_Ll.prototype.reset=function(){this.$=0;this.Ca=this.ma=!1}; s_Ll.prototype.suspend=function(){this.Ca=!0};var s_bpa=function(a,b){b=b||0;var c=a.Ea[b];return c?c.clientX:a.Db[a.ka[b||0]]},s_cpa=function(a,b){b=b||0;var c=a.Ea[b];return c?c.clientY:a.rb[a.ka[b||0]]};
var s_Ml=function(a,b,c){s_Ll.call(this,b,c,1);this.Na=a;this.Ia=new s_Joa};s_f(s_Ml,s_Ll);s_Ml.prototype.nb=function(a){s_Koa(this.Ia,this.qa[0],this.Wa[0],a.timeStamp);this.Lb=this.qa[0];this.Za=this.Wa[0]};s_Ml.prototype.Mc=function(a){return this.Na.Za(a)};s_Ml.prototype.Ma=function(a){this.Lb=this.qa[0];this.Za=this.Wa[0];s_Noa(this.Ia,s_bpa(this),s_cpa(this),a.timeStamp);this.Na.Pb(a);a.preventDefault()};
s_Ml.prototype.Ja=function(a){a&&(this.Xa=s_Ooa(this.Ia,this.Db[this.ka[0]],this.rb[this.ka[0]],a.timeStamp)||void 0,a.preventDefault());this.Na.Kb(a);var b=this.qa[0],c=this.Wa[0];a&&s_Ioa()?a.preventDefault():s_il(b,c,void 0)};var s_dpa=function(a){return s_bpa(a)-a.Lb},s_epa=function(a){return Math.abs(s_cpa(a)-a.Za)>Math.abs(s_dpa(a))};
var s_Nl=function(a,b,c){s_Ll.call(this,b,c,2);this.Ia=a};s_f(s_Nl,s_Ll);s_Nl.prototype.nb=s_b;s_Nl.prototype.Mc=function(a){return this.Ia.ha(a)};s_Nl.prototype.Ma=function(a){this.Ia.ka(a);a.preventDefault()};s_Nl.prototype.Ja=function(a){this.Ia.$(a);a&&a.preventDefault()};
var s_Ol=function(a){this.ma=a;this.Aa=this.ma.va();this.ka={};this.ha={};this.$=[]},s_fpa=[s_Ml,s_Nl],s_gpa=function(a,b){var c=a.$[0];if(c)return c;c=new s_fpa[0](b,a.ka,a.ha);return a.$[0]=c};
s_Ol.prototype.Wa=function(a){var b=s_dl(a),c=b.length,d;for(d in this.ka){for(var e=0;e<c;e++)if(d==s_Il(b[e])){var f=!0;break}f||s_hpa(this,+d)}b=s_el(a);c=b.length;for(e=0;e<c;e++)d=s_Il(b[e]),s_a(this.ka[d])&&s_hpa(this,+d);c=!0;e=this.$.length;for(b=0;b<e;b++)if((d=this.$[b])&&d.$!=d.ha){c=!1;break}if(!c&&this.ma.iG(a)){c=s_el(a);d=c.length;for(b=0;b<d;b++){var f=c[b],g=s_Il(f);this.ka[g]=f.clientX;this.ha[g]=f.clientY}for(b=0;b<e;b++)(d=this.$[b])&&d.iG(a)}};
s_Ol.prototype.qa=function(a){for(var b=!0,c=this.$.length,d=0;d<c;d++){var e=this.$[d];if(e&&0<e.$){b=!1;break}}if(!b){for(d=0;d<c;d++)(e=this.$[d])&&e.OW(a);a=s_el(a);b=a.length;for(d=0;d<b;d++)c=a[d],e=s_Il(c),s_a(this.ka[e])&&(this.ka[e]=c.clientX,this.ha[e]=c.clientY)}};
s_Ol.prototype.Ea=function(a){for(var b=s_el(a),c=b.length,d,e=0;e<c;e++){var f=b[e],f=s_Il(f);s_a(this.ka[f])&&(this.ma.Xa(a),d=!0)}if(d){d=this.$.length;for(e=0;e<d;e++)if(f=this.$[e]){var g=a;if(!f.Ca&&0<f.$&&s_apa(f,g)){f.ma&&f.Ja(g);for(var g=f.$,k=0,l=0;l<g;l++)if(f.Ea[l]){var m=f;m.ka.splice(l-k,1);m.$--;m.ma=!1;k++}}}for(e=0;e<c;e++)f=b[e],f=s_Il(f),s_a(this.ka[f])&&(delete this.ka[f],delete this.ha[f])}};
var s_hpa=function(a,b){a.ma.Xa(null);for(var c=a.$.length,d=0;d<c;d++){var e=a.$[d];if(e){var f=void 0;if(!e.Ca&&0<e.$){for(var g=0;g<e.$;g++)if(e.ka[g]==b){f=g;break}s_a(f)&&(e.ma&&e.Ja(null),e.ka.splice(f,1),e.$--,e.ma=!1)}}}delete a.ka[b];delete a.ha[b]};s_Ol.prototype.enable=function(a,b){var c=s_c(this.Ea,this);s_poa(this.Aa,s_c(this.Wa,this),s_c(this.qa,this),c,c,a,b)}; s_Ol.prototype.reset=function(){for(var a in this.ka)delete this.ka[Number(a)],delete this.ha[Number(a)];for(a=0;a<this.$.length;a++){var b=this.$[a];b&&b.reset()}};

s_C("sy96");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy100");var s_lpa="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix(""),s_mpa=s_Qb?"webkitTransitionEnd":"transitionend",s_npa=function(a,b,c,d){a.style[s_kpa]=(c||s_Pl)+" "+b+"ms "+(d||"ease-in-out")},s_Tl=function(a,b,c){a.style[s_Ql]=s_Sl(b,c)},s_Sl=function(a,b){a=s_oa(a)?a+"px":a||"0";b=s_oa(b)?b+"px":b||"0";return s_lpa?"translate3d("+a+","+b+",0)":"translate("+a+","+b+")"};

s_C("sy100");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy87");var s_jl=function(a,b,c){this.type=a;this.$=b;this.target=c},s_Qoa=function(a,b,c,d){s_jl.call(this,1,a,b);this.x=c;this.y=d};s_f(s_Qoa,s_jl);var s_kl=function(a,b,c,d,e,f,g,k,l,m){s_jl.call(this,3,a,b);this.direction=c;this.touches=d;this.ka=e;this.ha=f;this.x=g;this.y=k;this.velocityX=l;this.velocityY=m};s_f(s_kl,s_jl);var s_ll=function(a,b,c,d,e,f,g){s_jl.call(this,4,a,b);this.scale=c;this.rotation=d;this.x=f;this.y=g};s_f(s_ll,s_jl); var s_ml=function(a,b,c,d,e,f){s_jl.call(this,a,b,c);this.touches=d;this.x=e;this.y=f};s_f(s_ml,s_jl);
var s_Roa=function(a,b,c){this.target=a;this.type=b;this.Kk=c},s_Soa=new s_se,s_Toa=0,s_nl=function(a,b,c){s_He(a,b,c);return new s_Roa(a,b,c)},s_ol=function(a,b){var c="gt"+s_Toa++;s_Soa.set(c,b);"_GTL_"in a||(a._GTL_=[]);a._GTL_.push(c);return c},s_pl=function(a){var b=s_Soa.get(a);if(b&&b.length){for(var c,d=null,e=0;e<b.length;e++)c=b[e],c instanceof s_Roa?(s_Ie(c.target,c.type,c.Kk),d=c.target):c();s_Soa.remove(a);d&&"_GTL_"in d&&s_2a(d._GTL_,a)}};
var s_ql=function(a,b,c,d){this.$=a;this.ka=b;this.x1=c;this.y1=d};s_ql.prototype.clone=function(){return new s_ql(this.$,this.ka,this.x1,this.y1)};s_ql.prototype.equals=function(a){return this.$==a.$&&this.ka==a.ka&&this.x1==a.x1&&this.y1==a.y1};var s_Uoa=function(a){var b=a.x1-a.$;a=a.y1-a.ka;return b*b+a*a},s_rl=function(a){return new s_ec(s_cc(a.$,a.x1,.5),s_cc(a.ka,a.y1,.5))};
var s_sl=function(){};s_f(s_sl,s_2d);var s_Voa=function(){return"DEFAULT_ID"};s_sl.prototype.ma=s_5d(s_Voa);s_sl.prototype.ha=s_5d(s_Voa);s_sl.prototype.$=s_5d(s_Voa);s_sl.prototype.qa=s_5d(s_Voa);
var s_Woa=function(a){return!a||0==a.x&&0==a.y?0:Math.abs(a.x)>Math.abs(a.y)?0<a.x?6:4:0<a.y?5:3},s_tl=function(a,b){return 0==b||2>=b&&a%2==b%2?!0:a==b},s_ul=function(a,b,c,d){a=180*Math.atan2(d-b,c-a)/Math.PI;0>a&&(a=360+a);return a},s_Xoa=function(a,b,c,d,e,f,g,k){a=Math.sqrt(s_Uoa(new s_ql(e,f,g,k)))/Math.sqrt(s_Uoa(new s_ql(a,b,c,d)));return isNaN(a)?1:isFinite(a)?a:10};
var s_vl=function(){s_7d(this)};s_3d(s_sl,s_vl);s_ia(s_vl);var s_Yoa=function(a,b){return s_vl.Sa().Mb.ma(a,b,void 0,void 0)},s_wl=function(a,b,c,d,e,f,g){return s_vl.Sa().Mb.ha(a,b,c,d,e,f,g)},s_Zoa=function(a,b,c,d){return s_vl.Sa().Mb.qa(a,b,c,d,1,!0)};

var s_zl=function(){};s_f(s_zl,s_sl);s_4d(s_zl,s_sl);s_zl.prototype.ma=function(a,b,c,d){c=[s_nl(a,"click",function(c){d&&c.stopPropagation();b(new s_Qoa(c,a,c.screenX,c.screenY))}),s_nl(a,"keydown",function(c){var d=c.which||c.keyCode||c.key,e=a.tagName.toUpperCase();"TEXTAREA"==e||"BUTTON"==e||"INPUT"==e||a.isContentEditable||c.ctrlKey||c.shiftKey||c.altKey||c.metaKey||13!=d&&32!=d&&3!=d||(32==d&&c.preventDefault(),b(c))})];return s_ol(a,c)};
s_zl.prototype.ha=function(a,b,c,d,e,f,g){var k=e||0,l,m,n,ba,t,w=new s_Joa,B,G=!1;e=function(a){G=a};var I=function(c){if(G){n=c.screenX;ba=c.screenY;var d=s_Noa(w,n,ba,c.timeStamp);t=s_Woa(d);s_tl(t,k)&&b(new s_kl(c,a,t,1,l,m,n,ba,d.x,d.y))}};B=function(b){if(s_tl(t,k)){s_Ie(a,"mousemove",I);s_Ie(a,"mouseup",B);s_Ie(a,"mouseout",B);var c=s_Ooa(w,n,ba,b.timeStamp);d&&d(new s_kl(b,a,t,1,l,m,b.screenX,b.screenY,c.x,c.y));g||s_il(l,m)}};e=[s_nl(a,"mousedown",function(b){l=n=b.screenX;m=ba=b.screenY;
s_Koa(w,l,m,b.timeStamp);c&&c(new s_kl(b,a,0,1,l,m,n,ba,0,0));s_He(a,"mousemove",I);s_He(a,"mouseup",B);s_He(a,"mouseout",B)}),s_nl(document.body,"mousedown",s_d(e,!0)),s_nl(document.body,"mouseup",s_d(e,!1))];return s_ol(a,e)};
s_zl.prototype.$=function(a,b,c,d,e){var f=!1,g=function(a){f=a},k,l=!1,m,n,ba,t,w,B=function(b){ba=b.screenX;t=b.screenY;w=s_ul(m,n,ba,t);var d=s_rl(new s_ql(m,n,ba,t));c&&c(new s_ll(b,a,1,0,0,d.x,d.y))},G=function(c){if(f){var d=c.screenX,e=c.screenY,g=s_rl(new s_ql(m,n,d,e));b(new s_ll(c,a,s_Xoa(m,n,ba,t,m,n,d,e),s_ul(m,n,d,e)-w,0,g.x,g.y))}};k=function(b){l=!1;s_Ie(a,"mousedown",B);s_Ie(a,"mousemove",G);s_Ie(a,"mouseup",k);s_Ie(a,"mouseout",k);if(d){var c=b.screenX,f=b.screenY,g=s_rl(new s_ql(m,
n,c,f));d(new s_ll(b,a,s_Xoa(m,n,ba,t,m,n,c,f),s_ul(m,n,c,f)-w,0,g.x,g.y))}e||s_il(m,n)};g=[s_nl(a,"click",function(b){m=b.screenX;n=b.screenY;l||(s_He(a,"mousedown",B),s_He(a,"mousemove",G),s_He(a,"mouseup",k),s_He(a,"mouseout",k),l=!0)}),s_nl(document.body,"mousedown",s_d(g,!0)),s_nl(document.body,"mouseup",s_d(g,!1))];return s_ol(a,g)};
s_zl.prototype.qa=function(a,b,c,d,e,f){var g,k,l,m=!1;e=function(a){m=a};var n=function(c){m&&b&&b(new s_ml(6,c,a,1,c.screenX,c.screenY))};l=function(b){s_Ie(a,"mousemove",n);s_Ie(a,"mouseup",l);s_Ie(a,"mouseout",l);d&&d(new s_ml(7,b,a,1,b.screenX,b.screenY));f||s_il(g,k)};e=[s_nl(a,"mousedown",function(b){g=b.screenX;k=b.screenY;c&&c(new s_ml(5,b,a,1,g,k));s_He(a,"mousemove",n);s_He(a,"mouseup",l);s_He(a,"mouseout",l)}),s_nl(document.body,"mousedown",s_d(e,!0)),s_nl(document.body,"mouseup",s_d(e, !1))];return s_ol(a,e)};

s_C("sy87");s_E();
}catch(e){_DumpException(e)}
try{
var s_3oa=function(a){var b;a:{b=s_Ja("transform");if(void 0===a.style[b]&&(b=s_Yc()+s_La(b),void 0!==a.style[b])){b=s_Zc()+"-transform";break a}b="transform"}return s_vd(a,b)||s_vd(a,"transform")};s_D("sy93");var s_4oa=s_kd(function(){return!s_Nb||0<=s_Ha(s_2oa,9)}),s_5oa=s_kd(function(){return s_Qb||s_Ob||s_Pb&&0<=s_Ha(s_2oa,10)||s_Nb&&0<=s_Ha(s_2oa,10)}),s_Gl=function(a){a=s_3oa(a);var b=s_6oa();return a&&b?(a=new b(a),new s_ec(a.m41,a.m42)):new s_ec(0,0)},s_Hl=function(a,b,c){s_4oa()&&(b=s_5oa()?"translate3d("+b+"px,"+c+"px,0px)":"translate("+b+"px,"+c+"px)",s_q(a,s_7oa(),b))},s_8oa=function(a){a=s_3oa(a);var b=s_6oa();return a&&b?(a=new b(a),new s_El(a.m11,a.m22,a.m33)):new s_El(0,0,0)},s_7oa=s_kd(function(){return s_Nb&& 9==s_Zaa?"-ms-transform":"transform"}),s_6oa=s_kd(function(){return s_a(s_ga.WebKitCSSMatrix)?s_ga.WebKitCSSMatrix:s_a(s_ga.MSCSSMatrix)?s_ga.MSCSSMatrix:s_a(s_ga.CSSMatrix)?s_ga.CSSMatrix:null});

s_C("sy93");s_E();
}catch(e){_DumpException(e)}
try{
var s_opa=function(a,b,c){a.style.left=b+"px";a.style.top=c+"px"},s_ppa=function(a,b,c,d,e,f,g,k){b="translate3d("+b+"px,"+c+"px,"+(d||0)+"px)";e&&(b+=" rotate("+e+"deg)");s_a(f)&&(b+=" scale3d("+f+","+f+",1)");a.style[s_Ql]=b;g&&(a.style[s_Ql+"OriginX"]=g+"px");k&&(a.style[s_Ql+"OriginY"]=k+"px")};s_D("sy98");
var s_qpa=1/3,s_rpa=2/3,s_spa=[s_qpa,s_rpa,s_rpa,1],s_tpa=function(a,b,c,d){if(s_dc(b,0))return s_spa;s_dc(a,b)?a=[0,0]:(b=(d-c*b)/(a-b),a=[b,b*a]);a=[a[0]/c,a[1]/d];c=a[0]*s_rpa;d=a[1]*s_rpa;return[c,d,c+s_qpa,d+s_qpa]};var s_upa=function(){this.Ia=s_c(this.Na,this);this.qa=this.Ea=0},s_vpa=7/60,s_wpa=7/60,s_xpa=1E3/60,s_ypa=.25*s_xpa,s_Ul=.01*s_xpa;s_=s_upa.prototype;s_.WB=function(){return 0};
s_.start=function(a,b,c,d){this.Ca=b;this.Wa=c;this.$=d.clone();this.ma=d.clone();b=s_zpa(a.x,this.$.x,this.Ca.x,this.Wa.x);if(0>b*a.x||!a.x&&b)this.qa=2;c=s_zpa(a.y,this.$.y,this.Ca.y,this.Wa.y);if(0>c*a.y||!a.y&&c)this.Ea=2;this.ka=new s_ec(b,c);if(Math.abs(this.ka.y)>=s_ypa||Math.abs(this.ka.x)>=s_ypa||this.qa||this.Ea){a=[];for(b=s_e();;){do this.$.y+=this.ka.y,this.$.x+=this.ka.x,this.Ga=Math.round(this.$.y),this.Da=Math.round(this.$.x),s_Apa(this,this.$.x,this.Ca.x,this.Wa.x,this.ka.x,this.qa,
!1),s_Apa(this,this.$.y,this.Ca.y,this.Wa.y,this.ka.y,this.Ea,!0),b+=s_xpa;while(this.Ga==this.ma.y&&this.Da==this.ma.x&&(Math.abs(this.ka.y)>=s_Ul||Math.abs(this.ka.x)>=s_Ul));if(0==this.qa&&0==this.Ea&&this.Ga==this.ma.y&&this.Da==this.ma.x)break;a.push(b,this.Da,this.Ga);this.ma.y=this.Ga;this.ma.x=this.Da}this.ha=a;if(this.ha.length)return this.Ja=window.setTimeout(this.Ia,this.ha[0]-s_e()),this.Ma=!0}};s_.CP=s_b;s_.stop=function(){this.Ma=!1;this.ha=[];window.clearTimeout(this.Ja);s_Bpa(this.Mb)};
s_.dA=function(){return this.Ma};s_.pO=function(a){this.Mb=a};var s_zpa=function(a,b,c,d){a=a*s_xpa*1.25;Math.abs(a)<s_ypa&&(b<c?(a=(c-b)*s_wpa,a=Math.max(a,s_Ul)):b>d&&(a=(b-d)*s_wpa,a=-Math.max(a,s_Ul)));return a},s_Apa=function(a,b,c,d,e,f,g){if(e){e*=.97;if(b<c)var k=c-b;else b>d&&(k=d-b);k?0>k*e?(f=2==f?0:1,e+=k*s_vpa):(f=2,e=0<k?Math.max(k*s_wpa,s_Ul):Math.min(k*s_wpa,-s_Ul)):f=0;g?(a.ka.y=e,a.Ea=f):(a.ka.x=e,a.qa=f)}}; s_upa.prototype.Na=function(){if(this.ha.length){var a=this.ha.splice(0,3);this.Mb.xc(a[1],a[2]);this.ha.length?(a=this.ha[0]-s_e(),this.Ja=window.setTimeout(this.Ia,a)):this.stop()}};
var s_Vl=function(){this.$=[]};s_Vl.prototype.ka=-5E-4;s_Vl.prototype.WB=function(){return 1};
s_Vl.prototype.start=function(a,b,c,d){var e=Math.abs(a.y)>=Math.abs(a.x),f=e?a.y:a.x;a=e?b.y:b.x;var g=e?c.y:c.x,k=e?d.y:d.x;b=s_bc(e?d.x:d.y,e?b.x:b.y,e?c.x:c.y);if(k<a||k>g)a=k<a?a:g,this.$.push(e?b:a,e?a:b,500,"ease-out");else if(.25<=Math.abs(f)){d=(c=0>f)?-this.ka:this.ka;var l=c?a-k:g-k,m=f;if(l){var m=f*f,n=2*d,ba=-m/n;Math.abs(ba)<Math.abs(l)?(l=ba,m=0):(m=Math.sqrt(m+n*l),m*=0>f?-1:1);this.Ea=m;this.ha=(m-f)/d;this.qa=l;f="cubic-bezier("+s_tpa(f,this.Ea,this.ha,this.qa).join(",")+")";k+=
this.qa;this.$.push(e?b:k,e?k:b,this.ha,f);m=this.Ea}0!=m&&(a=c?a:g,k=50*m,g=a+k,this.ha=2*k/(m+0),f="cubic-bezier("+s_tpa(m,0,this.ha,k).join(",")+")",this.$.push(e?b:g,e?g:b,this.ha,f),this.$.push(e?b:a,e?a:b,500,"ease-out"))}if(this.$.length)return this.ma=!0,s_Cpa(this),!0};var s_Cpa=function(a){var b=a.$,c=b.shift(),d=b.shift(),e=b.shift(),b=b.shift();a.Mb.xc(c,d,e,b)};s_Vl.prototype.CP=function(){this.ma&&(this.$.length?s_Cpa(this):(this.ma=!1,s_Bpa(this.Mb)))}; s_Vl.prototype.stop=function(){this.ma=!1;this.$=[];s_Bpa(this.Mb)};s_Vl.prototype.dA=function(){return this.ma};s_Vl.prototype.pO=function(a){this.Mb=a};
var s_Dpa=function(){},s_Epa=new s_Dpa;s_Dpa.prototype.$=1;var s_Xl=function(a,b,c,d,e,f,g,k){this.Aa=a;this.Mc=a.parentNode;this.Aa.addEventListener(s_mpa,s_c(this.Yd,this),!1);this.Rb=new s_Ol(this);this.Rb.enable(f);this.Wa=s_gpa(this.Rb,this);var l;switch(s_Epa.$){case 0:l=new s_upa;break;case 1:l=new s_Vl}l.pO(this);this.ha=l;this.Ea=null;this.rb=!!b;this.Rv=!!c;this.Cc=d;this.Da=e||1;this.ka=s_Wl.clone();this.Ga=s_Wl.clone();this.Na=s_Wl.clone();this.$=s_Wl.clone();this.Db=1==this.Da?s_ppa:s_opa;a=s_a(k)?k:this.ka.y;this.$.x=s_a(g)?g:this.ka.x;this.$.y=
a;this.Da=g=this.Da;this.Db=1==g?s_ppa:s_opa;1!=g&&(this.Aa.style[s_kpa]="",this.Aa.style[s_Ql]="");2!=g&&s_opa(this.Aa,0,0);this.Db(this.Aa,this.$.x,this.$.y);this.Cd=[]},s_Fpa=s_Kl("scroller:scroll_start"),s_Yl=s_Kl("scroller:scroll_end"),s_Gpa=s_Kl("scroller:drag_end"),s_Hpa=s_Kl("scroller:content_moved"),s_Ipa=s_Kl("scroller:decel_start"),s_Wl=new s_ec(0,0);s_Xl.prototype.Dd=null;s_Xl.prototype.Ja=!0;
s_Xl.prototype.reset=function(){this.stop();this.Wa.reset();s_Zl(this,this.Aa,0);this.Ca();s__l(this,s_Pd(document.body)?this.ma.x:this.ka.x,this.ka.y)};
s_Xl.prototype.Ca=function(){this.qa=new s_ic(this.Mc.offsetWidth,this.Mc.offsetHeight);this.nb=new s_ic(this.Ed||this.Aa.scrollWidth,this.Vc||this.Aa.scrollHeight);var a=new s_ic(Math.max(this.qa.width,this.nb.width),Math.max(this.qa.height,this.nb.height)),b=s_Pd(document.body),c;b?(c=a.width-this.qa.width,c=this.Ga.x?Math.min(c,this.Ga.x):c):c=s_Wl.x-this.Ga.x;this.ka=new s_ec(c,s_Wl.y-this.Ga.y);this.ma=new s_ec(b?this.Na.x:Math.min(this.qa.width-a.width+this.Na.x,this.ka.x),Math.min(this.qa.height-
a.height+this.Na.y,this.ka.y));s_Jpa(this)};var s_Jpa=function(a){var b=s_bc(a.$.x,a.ma.x,a.ka.x),c=s_bc(a.$.y,a.ma.y,a.ka.y);a.$.x==b&&a.$.y==c||s__l(a,b,c)},s__l=function(a,b,c){a.$.x=b;a.$.y=c;a.Db(a.Aa,b,c);s_Jl(a.Aa,s_Hpa,a)};s_Xl.prototype.mi=function(a,b,c,d){s_a(c)&&1==this.Da&&s_Zl(this,this.Aa,c,s_Pl,d);s__l(this,a,b)};s_Xl.prototype.Yd=function(a){a.target==this.Aa&&(this.Ia=!1,this.ha.CP())};
s_Xl.prototype.stop=function(){if(this.ha.dA())if(2==this.Da)this.ha.stop();else{var a=s_Rl(this.Aa);if(this.Ia){this.$.x=a.m41;this.$.y=a.m42;this.Ma=!0;var b=this;window.setTimeout(function(){var c=s_Rl(b.Aa);s_Zl(b,b.Aa,0);window.setTimeout(function(){b.Ma=!1},0);var d=c.m41+2*(c.m41-a.m41),c=c.m42+2*(c.m42-a.m42),d=s_bc(d,b.ma.x,b.ka.x),c=s_bc(c,b.ma.y,b.ka.y);s_Kpa(b,d,c)},0)}else s_Kpa(this,a.m41,a.m42)}};var s_Kpa=function(a,b,c){a.ha.stop();s__l(a,b,c)};
s_Xl.prototype.iG=function(a){if(this.Wa.ma)return!0;this.Ca();this.ha.dA()?(a.preventDefault(),this.Yb||a.stopPropagation(),this.stop()):s_Zl(this,this.Aa,0);this.Ub=this.$.clone();s_Jpa(this);return!0};s_Xl.prototype.Xa=function(){};s_Xl.prototype.Za=function(a){var b=s_epa(this.Wa);if(this.De&&!b||!this.rb&&(!s_Lpa(this)||b))return!1;for(var b=0,c;c=this.Cd[b];++b)if(!c.ka(this,a))return!1;for(b=0;c=this.Cd[b];++b)c.$(this,a);return!0};
s_Xl.prototype.Pb=function(a){this.Ja||a.stopPropagation();var b;a=this.Wa;b=s_cpa(a)-a.Za;if(!this.Ma){var c=this.Ub;a=c.x+s_dpa(this.Wa);a=s_Lpa(this)?s_Mpa(a,this.ma.x,this.ka.x):0;b=c.y+b;b=this.rb?s_Mpa(b,this.ma.y,this.ka.y):0;this.Lb||(this.Lb=!0,s_Jl(this.Aa,s_Fpa,this));s__l(this,a,b)}};var s_Lpa=function(a){return a.Rv&&a.qa.width<a.nb.width},s_Mpa=function(a,b,c){a<b?a-=(a-b)/2:a>c&&(a-=(a-c)/2);return a};
s_Xl.prototype.Kb=function(){var a=this.Wa.Xa;s_Jl(this.Aa,s_Gpa,this);if(a&&this.Cc&&!this.Ia){var b;s_Lpa(this)||(a.x=0);this.rb||(a.y=0);b=this.ha.start(a,this.ma,this.ka,this.$)}b?s_Jl(this.Aa,s_Ipa,this):(s_Jpa(this),s_Jl(this.Aa,s_Yl,this),this.Lb=!1)};var s_Zl=function(a,b,c,d,e){a.Ia=0<c;s_npa(b,c,d,e)};s_Xl.prototype.va=function(){return this.Aa};s_Xl.prototype.getFrame=function(){return this.Mc};s_Xl.prototype.xc=s_Xl.prototype.mi; var s_Bpa=function(a){s_Zl(a,a.Aa,0);s_Jl(a.Aa,s_Yl,a);a.Lb=!1};

s_C("sy98");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy101");
s_C("sy101");s_E();
}catch(e){_DumpException(e)}
try{
var s_Npa=function(a,b){b?(s_w(a,"checked"),a.setAttribute("aria-checked","true")):(s_x(a,"checked"),a.setAttribute("aria-checked","false"))},s_Opa=function(a){var b;s_t(a,"s")&&(b=a.previousSibling);var c=null!==a&&s_v(a,"checked");s_Npa(a,!c);b&&!c&&s_Npa(b,!1);a.hasAttribute("url")&&(b=a.getAttribute("url")+"&ei="+google.getEI(a),(a=s_t(a,"ved"))&&(b+="&ved="+a),s_6e(b))},s_Ppa=function(){var a={cdr_min:"cd_min",cdr_max:"cd_max"},b=s_i("ctbs");if(b)for(var c in a){var d=s_9oa(s_i(c).value),d=d.replace(/^\s+|\s+$/g, "");b.value=b.value.replace(new RegExp("("+a[c]+":)([^,]*)"),"$1"+d)}return!0};s_D("sy88");
var s_1l=function(a,b,c,d){this.jj=a;this.$=b;this.ma=!!c;this.Zd=d?d:null;this.ka=null;this.ha=s_Yoa(this.jj,s_c(this.Ea,this));s_Xe(93,s_c(this.hide,this));s_0l.push(this);a=this.jj.querySelectorAll(".mn-hd-txt");0<a.length&&this.jj.setAttribute("aria-label",a[0].innerHTML)},s_0l=[];s_1l.prototype.hide=function(){this.$.setAttribute("aria-expanded","false");s_x(this.$,"hdtb-mn-o");s_w(this.$,"hdtb-mn-c");this.ka&&s_Ie(document.body,"click",this.ka)};
s_1l.prototype.Ea=function(a){var b=s_v(this.$,"hdtb-mn-c");this.ma&&s_z(this.$,[this.$],[b]);b?(s_u(93),this.$.setAttribute("aria-expanded","true"),s_ef(a.$||a),this.Zd&&this.Zd(this.jj,this.$),s_x(this.$,"hdtb-mn-c"),s_w(this.$,"hdtb-mn-o"),this.ka=s_c(this.qa,this),s_He(document.body,"click",this.ka),b=this.$.querySelectorAll(".hdtb-mitem .qs"),0<b.length&&("keydown"==a.type&&a.preventDefault(),b[0].focus()),b=this.$.querySelectorAll(".hdtbSel"),0<b.length&&("keydown"==a.type&&a.preventDefault(), b[0].focus())):this.hide()};s_1l.prototype.qa=function(a){s_Mc(this.$,s_df(a.$||a))||this.hide()};s_1l.prototype.dispose=function(){s_pl(this.ha);this.ha="";this.ka&&(s_Ie(document.body,"click",this.ka),this.ka=null)};
var s_Upa=function(a,b,c){this.jj=a;this.$=b;this.ha=s_i("hdtb-rst");c&&(this.Zd=c);this.ka=s_i("appbar");this.ma=[];a=this.$.querySelectorAll(".hdtb-mn-hd");b=this.$.querySelectorAll("ul.hdtbU");c=a.length;for(var d=0;d<c;d++){var e=a[d],f=b[d];e&&f&&this.ma.push(new s_1l(e,f,!1,s_Qpa))}s_Yoa(this.jj,s_c(this.Ea,this));this.ha&&s_Yoa(this.ha,s_c(this.qa,this));s_Rpa(this);s_Spa(this);s_Tpa(this,s_2l(this))},s_Qpa=function(a,b){var c=document.body||document.documentElement,d=s_Pd(c),e=d?"right":"left",
f=s_Ed(a),g=s_yd(a).y,k=s_Ed(s_l("hdtb-mn-cont"))-s_Ed(s_i("hdtbMenus")),l=f-15-k;s_l("gsa-tools-card")&&(l-=s_Ed(s_i("hdtbMenus")));a=s_r(a);d&&(l=s_r(c).width-f-a.width-15+k-20);c=a.height+g+"px";d=a.width+30+30+"px";b.style[e]=l+"px";s_q(b,{top:c,"min-width":d})},s_Vpa=function(a){for(var b=a.ma.length,c=0;c<b;++c)a.ma[c].hide()},s_Wpa=function(a){var b=s_l("gsa-tools-card");b&&s_s(b,!0);a.Zd&&a.Zd();a.$.setAttribute("aria-expanded","true");s_Tpa(a,!0);s_x(a.$,"hdtb-td-c");s_x(a.$,"hdtb-td-h");
s_Qf(s_c(function(){s_w(this.$,"hdtb-td-o");this.ka&&s_w(this.ka,"hdtb-ab-o");s_Rpa(this);s_Spa(this)},a));a=a.$.querySelectorAll(".hdtb-mn-hd");0<a.length&&a[0].focus()},s_Xpa=function(a){s_Tpa(a,!1);s_Vpa(a);a.$.setAttribute("aria-expanded","false");s_Qf(s_c(function(){s_x(this.$,"hdtb-td-o");s_w(this.$,"hdtb-td-c");this.ka&&s_x(this.ka,"hdtb-ab-o");s_Rpa(this);s_Spa(this)},a));a.jj.focus();(a=s_l("gsa-tools-card"))&&s_s(a,!1)};
s_Upa.prototype.Ea=function(){var a=!s_2l(this);s_z(this.jj,[this.$],[a]);var b=s_i("tndd");b&&(b.style.webkitTransform="translate3d(0,-"+s_t(b,"height")+"px,0)");var b=s_i("htnmenu"),c=s_i("htnoverlay");b&&c&&(b.style.webkitTransform="translate3d(0,0,0)",c.style.opacity=0,s_x(document.body,"fxd"));a?s_Wpa(this):s_Xpa(this);for(a=0;a<s_0l.length;a++)s_0l[a].hide()};s_Upa.prototype.qa=function(){s_6e(this.ha.getAttribute("data-url"))};
var s_2l=function(a){return"hdtb-td-o"==a.$.className},s_Rpa=function(a){var b=s_i("botabar");b&&s_Nd(b)&&(s_r(b),b.style.marginTop=s_2l(a)?a.$.offsetHeight+"px":0);a.ka&&s_y(a.ka,"hdtb-ab-o",s_2l(a))},s_Spa=function(a){var b=s_i("epbar"),c=s_i("slim_appbar");c&&!s_Nd(c)&&b&&(b.style.marginTop=s_2l(a)?10+a.$.offsetHeight+"px":"10px")},s_Tpa=function(a,b){s_y(a.jj,"hdtb-tl-sel",b)};
var s_3l=function(a){this.Ia=this.Ga=null;this.Da=s_K(a,2);this.$=s_K(a,9);this.Wa=s_K(a,3);this.ha=s_K(a,1);this.Za=!1;this.ma=s_i("hdtb-more");this.qa=s_i("hdtb-more-mn");this.Db=s_i("hdtb-tls");this.Ea=s_i("hdtbMenus");this.Ca=s_i("hdtb-sc");this.Ja=s_i("hdtb-s")||s_i("hdtb-msb");this.ma&&this.qa&&new s_1l(this.ma,this.qa,!0,s_c(this.Ma,this));this.Da&&!this.$&&this.Ja&&(this.Ga=s_Ypa(this.Ja));this.ma&&this.qa&&this.$&&this.ha&&s_He(window,"resize",s_c(this.Ma,this,this.ma,this.qa));this.Db&&
this.Ea&&new s_Upa(this.Db,this.Ea,s_c(this.Xa,this));this.Wa&&null!==this.Ea&&s_v(this.Ea,"hdtb-td-o")&&s_Zpa(this);if(!this.Da){var b=s_i("hdtb-s");if(b){a=4;for(var b=b.childNodes,c=0;c<b.length;++c)a+=b[c].clientWidth;b=s_i("top_nav");null!==b&&(c=s_Ma(s_td(b,"minWidth")||s_ud(b,"minWidth")),!c||a>c)&&(b.style.minWidth=a+"px")}}a=s_i("hdtb");null===a||s_He(a,"keydown",s_c(this.Na,this));s_dh("tnv",{cb:s_Opa,scf:s_Ppa});this.Da&&this.Ca&&s_dh("tnv",{msc:s_c(this.rb,this)})};s_f(s_3l,s_h);
s_3l.prototype.Ha=function(){for(var a=0;a<s_0l.length;a++)s_0l[a].dispose();s_0l=[];this.Ia=this.Ga=null;this.ha=this.Wa=!1;a=s_i("hdtb");null===a||s_Ie(a,"keydown",this.Na)};s_3l.prototype.Na=function(a){this.Za||9!=a.keyCode||(s_x(s_i("hdtb"),"notl"),this.Za=!0)};s_3l.prototype.Ma=function(a,b){var c=s_pf(),d=this.ha!=c,c=d?"right":"left",e=Math.max(0,s_Ed(a));this.ha&&!this.$?e=0:d&&(d=s_r(document.body||document.documentElement).width,e=Math.max(0,d-e-s_r(a).width));b.style[c]=e+"px"};
s_3l.prototype.Xa=function(){!this.Ia&&this.Wa&&s_Zpa(this)};var s_Ypa=function(a){var b=s_sd(a,"transform")?s_Gl(a).x:null,c=new s_Xl(a,!1,!0,!0,1,!0);c.Ja=!0;c.Yb=!0;c.Ca();a=s_l("hdtb-msel",a)||s_l("hdtb-tsel",a);var d=0;null!=b?d=b:a&&(b=document.body||document.documentElement,d=s_Pd(b)?Math.min(s_Ed(a)-s_Ed(b),c.ka.x):Math.max(Math.min(c.ka.x,-s_Ed(a)+15),c.ma.x));c.mi(d,0);s_He(document,"orientationChange",c.Ca);return c},s_Zpa=function(a){var b=s_k("hdtb-mn-cont")[0];b&&(a.Ia=s_Ypa(b))}; s_3l.prototype.rb=function(a,b,c){s_Ib()&&!s_Ab()&&c.target&&"A"==c.target.nodeName&&s_q(this.Ca,"overflow-scrolling","auto");a=this.$?s_Bl(this.Ca):Math.abs(this.Ga.$.x);(b=s_7f("session","tnv"))&&b.set("hdtb-pos",a)};
var s__pa=function(a){s_I(this,a,0,10,null,null)};s_f(s__pa,s_H);
s_C("sy88");s_E();
}catch(e){_DumpException(e)}
try{
var s_0pa=function(a){s_3l.call(this,a.$.$(s__pa,"top_nav"))};s_f(s_0pa,s_3l);s_D("tnv");var s_1pa=function(a){this.$=a};s_U(function(a){s_T(a,"t-js5htJpaNsk",s_0pa,s_1pa,null,function(a,c){s_0pa.call(a,c)})});

s_C("tnv");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy111");
s_C("sy111");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy112");var s_Aqa=function(){return""},s_Bqa=function(){};
s_C("sy112");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy44");var s_mja;s_vb("A AREA BUTTON HEAD INPUT LINK MENU META OPTGROUP OPTION PROGRESS STYLE SELECT SOURCE TEXTAREA TITLE TRACK".split(" "));
var s_Zi=function(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")},s__i=function(a){return a.getAttribute("role")||null},s_0i=function(a,b,c){s_la(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(s_mja||(s_mja={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=s_mja,b in c?a.setAttribute(d,c[b]): a.removeAttribute(d)):a.setAttribute(d,c)},s_1i=function(a,b){a.removeAttribute("aria-"+b)},s_2i=function(a,b){a=a.getAttribute("aria-"+b);return null==a||void 0==a?"":String(a)},s_nja=function(a,b){var c="";b&&(c=b.id);s_0i(a,"activedescendant",c)};

s_C("sy44");s_E();
}catch(e){_DumpException(e)}
try{
var s_cj=function(a,b,c,d,e){d=d||("string"==typeof b?"":s_Qe(b));e=e||("string"==typeof c?"":s_Qe(c));a.Ef.push({bq:d,targetElement:b,mW:e,pda:c,oC:2})},s_dj=function(a,b,c){a=a.querySelectorAll('[jsaction^="'+b+':"], [jsaction*=";'+b+':"], [jsaction*=" '+b+':"]');for(var d=0;d<a.length;++d){var e=a[d],f;a:{f=e;for(var g=a,k=0;k<g.length;++k){var l=g[k];if(l!=f&&s_Gfa(l,f)){f=!0;break a}}f=!1}f||s_2g(e,b,c)}},s_ej=function(a){return s_a(a.lastElementChild)?a.lastElementChild:s_Cba(a.lastChild,!1)},
s_wja=function(a,b){for(var c in a)if(!b.call(void 0,a[c],c,a))return!1;return!0},s_xja=function(a){if(!arguments.length)return[];for(var b=[],c=arguments[0].length,d=1;d<arguments.length;d++)arguments[d].length<c&&(c=arguments[d].length);for(d=0;d<c;d++){for(var e=[],f=0;f<arguments.length;f++)e.push(arguments[f][d]);b.push(e)}return b};s_D("sy51");
var s_V=function(a){a=a.XM;var b=a.rootElement;b||(b=a.rootElement=s_l(a.uN));return b},s_yja=function(a){for(;!a.VCa;)if(a=a.parentElement,!a)return null;return a.VCa},s_gj=function(a){a=s_V(a);s_fj(a)},s_fj=function(a){(a=s_yja(a))&&a.render()},s_hj=function(a,b,c,d){s_2g(s_V(a),b,c,d)},s_zja=function(a){a=s_Ze(a);for(var b=0,c=a.length;b<c;b++){var d=a[b];if(s_ua(d,"r-"))return d.substring(2)}return null},s_Aja=function(a){a=s_zja(a);s_vha(a,!0)},s_ij=function(a){if(a){var b=a.__ctx;return b?b.bP()|| null:(a=s_zja(a))?s_vha(a):null}return null},s_jj=function(a){var b=a.__ctx;if(b)return(a=b.bP())?s_B(a):s_jf(null);(a=s_zja(a))?(a=s_gi.$[a]||null)?(a.controller||s_uha(a),a.YS||(a.YS=s_lf(),s_7ga(a)),a=a.YS.$):a=s_jf(null):a=s_jf(null);return a};

s_C("sy51");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy109");var s_Dm=function(a){this.$=a};s_f(s_Dm,s_4l);s_Dm.prototype.play=function(){return s_hra(this)||s_B()};s_Dm.prototype.finish=function(){s_hra(this)};var s_hra=function(a){var b;a.$&&(b=a.$());a.$=null;return b};var s_Em=function(a){this.$=a;this.Je=[]};s_Em.prototype.add=function(a){s_pa(a)?this.Je.push(new s_Dm(a)):a&&this.Je.push(a);return this};s_Em.prototype.Pc=function(){for(var a=[],b=0,c;c=this.Je[b];b++)c instanceof s_Em?a.push(c.Pc()):a.push(c);return new this.$(a)};

s_C("sy109");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy113");var s_1=function(){this.Xa=s_lf();this.Ga=null;this.Za=-1;this.Ed=this.Vc=this.Ia=!1;this.Dd=null;this.$=""};s_f(s_1,s_4l);s_1.prototype.getChildren=function(){return this.Ga?[this.Ga]:[]};s_1.prototype.play=function(){s_ira(this);this.nb();this.fD();return this.Xa.$};s_1.prototype.finish=function(){this.Ia||(s_ira(this),this.nb(),this.Ga.finish(),this.Lb(),this.Xa.resolve(null))};var s_ira=function(a){a.Ga||a.Ia||(a.measure(),a.Ga=a.jd())};
s_1.prototype.nb=function(){this.Vc||this.Ia||(this.Vc=!0,this.Cb())};s_1.prototype.fD=function(a){if(!this.Ed&&!this.Ia){this.Ed=!0;var b=s_Aqa(this.$),c=this.Hf();this.Za=window.setTimeout(s_c(this.Ze,this),c);this.Ga.play().then(s_c(this.Be,this,!!a,b))}return this.Xa.$};s_1.prototype.Be=function(a,b,c){s_jra(this);a||this.Lb();s_Bqa(b);this.Xa.resolve(c)};s_1.prototype.Ze=function(){this.Za=-1;this.Ga.finish()};var s_jra=function(a){-1!=a.Za&&(window.clearTimeout(a.Za),a.Za=-1)}; s_1.prototype.Lb=function(){this.Ia||(this.Ia=!0,s_jra(this),this.Nc())};s_1.prototype.Nc=s_b;

s_C("sy113");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy45");var s_3i=function(a){this.ka=a;this.$=[]},s_4i=function(a){for(var b=a.ka;b&&b!=document.body;){var c=s_Lc(b);if(c){var d=s_Gc(c);s_g(d,function(a){a==b||s_2i(a,"hidden")||(s_0i(a,"hidden",!0),this.$.push(a))},a)}b=c}},s_5i=function(a){s_g(a.$,function(a){s_1i(a,"hidden")});a.$=[]};

s_C("sy45");s_E();
}catch(e){_DumpException(e)}
try{
var s_Bja=function(a,b){return a.left<=b.left+b.width&&b.left<=a.left+a.width&&a.top<=b.top+b.height&&b.top<=a.top+a.height},s_kj=function(a){return new s_if(function(b){var c=a.length,d=[];if(c)for(var e=function(a,e,f){c--;d[a]=e?{$sa:!0,value:f}:{$sa:!1,reason:f};0==c&&b(d)},f=0,g;f<a.length;f++)g=a[f],s_Fda(g,s_d(e,f,!0),s_d(e,f,!1));else b(d)})},s_Cja=function(a,b){a=String(a).toLowerCase();b=String(b).toLowerCase();return a<b?-1:a==b?0:1},s_lj=function(a){if(!a.getBoundingClientRect)return null;
a=s_lca(s_gca,a);return new s_ic(a.right-a.left,a.bottom-a.top)},s_Dja=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],g=arguments[b];g;)f.unshift(g),g=g.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){for(var g=d[0][b],k=1;k<c;k++)if(g!=d[k][b])return f;f=g}return f},s_Eja=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,s_Fja=function(a){if(a.__ctx)return null;
a=(a=s_zja(a))?(a=s_gi.$[a]||null)?a.dom:null:null;return a},s_mj=function(a,b){return a==b||!(!a||!b)&&a instanceof b.constructor&&s_Jga(a.Oa(),b.Oa())},s_Gja=function(a,b,c){var d=0;return function(e){s_ga.clearTimeout(d);var f=arguments;d=s_ga.setTimeout(function(){a.apply(c,f)},b)}},s_nj=function(a){return Array.prototype.join.call(arguments,"")};s_D("sy52");
var s_W=function(a){this.Ga=a;this.Da=a.XM.Yo||""};s_W.prototype.hb=function(){return s_V(this.Ga)};var s_Hja=function(a,b,c){b="."+a.Da+"-"+b;c&&(b+=",."+a.Da+"-"+c);return b},s_X=function(a,b,c){return a.hb().querySelector(s_Hja(a,b,c))},s_oj=function(a,b,c){return a.hb().querySelectorAll(s_Hja(a,b,c))},s_Y=function(a,b){return(a=s_X(a,b,void 0))?s_jj(a):s_jf(null)};s_W.prototype.AY=function(a){return(a=s_X(this,a,void 0))&&s_ij(a)}; var s_pj=function(a,b){var c=[];s_g(s_oj(a,b,void 0),function(a){c.push(s_jj(a))},a);return c};

s_C("sy52");s_E();
}catch(e){_DumpException(e)}
try{
s_D("em12");
s_C("em12");s_E();
}catch(e){_DumpException(e)}
try{
var s_Fm=function(a,b){b=a.lK()>b.lK()?b.width/a.width:b.height/a.height;return a.scale(b)},s_kra=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)},s_lra=function(a,b){b=s_Wa(a,b,void 0);return 0<=b?(s_1a(a,b),!0):!1};s_D("sy114");
var s_Gm=function(a){this.Je=s_Ra(a,s_ka);this.$=Array(this.Je.length)};s_f(s_Gm,s_4l);var s_Hm=function(){return new s_Em(s_Gm)};s_Gm.prototype.play=function(){var a=[],b=[],c=[];s_g(this.Je,function(d){d instanceof s_1?(s_ira(d),b.push(s_c(d.nb,d)),c.push(s_c(d.Lb,d)),a.push(s_c(d.fD,d,!0))):a.push(s_c(d.play,d))});s_g(b,function(a){a()});var d=s_Sa(a,function(a,b){return a().then(s_c(function(a){this.$[b]=!0;return a},this))},this),d=s_kf(d);d.then(function(){s_g(c,function(a){a()})});return d}; s_Gm.prototype.finish=function(){var a=s_Sa(this.Je,function(a,c){return this.$[c]?s_b:a instanceof s_1?(s_ira(a),function(){a.nb();a.finish()}):s_c(a.finish,a)},this);s_g(a,function(a){a()})};s_Gm.prototype.getChildren=function(){return this.Je};

s_C("sy114");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sdpm");var s_qrd=function(a){this.Fa=a;s_hj(this,"dp_menu_reg_caption")};var s_N2=function(a,b,c,d,e){s_1.call(this);this.Pa=e;this.ha=a;this.qa=s_Lc(a);this.Db=c;this.Ea=b;this.Ma=d;this.ma=null;this.fe=s_m("DIV");this.ka=1==e?b:c;this.Da=this.Na=0;this.Wa=[];this.Ca=[];this.Ja=null};s_f(s_N2,s_1);
s_N2.prototype.measure=function(){var a=s_qc("g-menu-item",null,this.ha),a=s_6a(a,0),b;this.Ea?b=a.indexOf(this.Ea):(this.Ea=a[0],b=0);for(var c=this.ha.getBoundingClientRect(),d=b-1;0<=d;d--){var e=a[d].getBoundingClientRect();if(e.bottom>c.top)this.Wa.push(a[d]);else break}for(d=b+1;d<a.length;d++)if(e=a[d].getBoundingClientRect(),e.top<c.bottom)this.Ca.push(a[d]);else break;a=this.qa.getBoundingClientRect();this.ka?(b=this.ka.getBoundingClientRect(),this.Da=b.top+b.height/2-(a.top+a.height/2),
this.Na=b.height/a.height,s_q(this.fe,{position:"fixed",top:b.top+"px",left:b.left+"px",width:b.width+"px",height:b.height+"px","background-color":"white","z-index":100}),this.ma=this.ka.cloneNode(!1),s_q(this.ma,{width:b.width+"px",height:b.height+"px"})):this.Da=-a.height/2};
s_N2.prototype.Cb=function(){if(this.ka){s_Dc(this.ma,this.ka);this.fe.appendChild(this.ka);s_Dc(this.fe,this.qa);var a=s_qc("g-ripple",null,this.ka)[0],b=this.Ma;this.Db&&this.Ma&&(b=this.Ma.detail.W2);if(a&&b){var b=s_Gd(b),c=s_Gd(a),d=new s_ec(b.x-c.x,b.y-c.y);s_jj(a).then(function(a){a.fka(d)},null,this)}}this.Ja=s_sd(this.ha,"overflow-y");s_q(this.ha,{"overflow-y":"hidden"});s_q(this.qa,{transform:"translate3d(0px, "+this.Da+"px, 0px) scale3d(1, "+this.Na+", 1)"})};
s_N2.prototype.jd=function(){var a=s_Hm(),b=150;if(1==this.Pa)s_g(this.Wa,function(b,c){a.add((new s_0(b,s_rrd(c))).translate(0,20,0,0,0,0).opacity(.001,1))},this),s_g(this.Ca,function(b,c){a.add((new s_0(b,s_rrd(c))).translate(0,-20,0,0,0,0).opacity(.001,1))},this);else{var c=s_kra(this.Wa,[this.Ea],this.Ca);s_g(c,function(b,c){a.add((new s_0(b,s_rrd(c))).translate(0,-20,0,0,0,0).opacity(.001,1))},this);b=Math.max(b,33*(c.length-1))}a.add(s_9l(s_am(new s_0(this.qa,{duration:b,zd:"cubic-bezier(.4,0,.2,1)"}),
1,1,1),0,0,0));return a.Pc()};var s_rrd=function(a){return{duration:150,zd:"cubic-bezier(0,0,.2,1)",Tc:33*a}};s_N2.prototype.Hf=function(){return 500};s_N2.prototype.Nc=function(){s_g(s_kra(this.Wa,[this.Ea],this.Ca),function(a){s_q(a,{opacity:"",transform:""})});null!=this.Ja&&s_q(this.ha,{"overflow-y":this.Ja});s_q(this.qa,{transform:""});this.ka&&(s_Dc(this.ka,this.ma),s_n(this.ma),s_n(this.fe))};
var s_trd=function(a,b){this.Fa=b;this.ka=a;this.Ea=[];this.Ga=this.qa=this.Da=this.Wa=!1;this.$=s_X(this.Fa,"Iba4lUJ1VEU");this.ha=this.Fa.Og();this.ma=null;this.Ca=new s_3i(this.$);s_Y(this.Fa,"ApRJQKtFf4g").then(s_c(function(){s_srd(this)},this));this.Ia=this.Ja=""};s_trd.prototype.He=function(){s_srd(this);return s_ij(this.$)};
var s_srd=function(a){if(!a.Wa){var b=s_ij(a.$).nm();b&&(b=s_ij(b),s_urd(a,b));a.Wa=!0}},s_xrd=function(a,b){if(a.ha){var c=s_V(a);a.Ja=s_sd(c,"width");a.Ia=s_sd(c,"height");s_Kd(c,s_r(c));s_Ec(a.ha,s_vrd(a),0)}var d=s_ij(a.$).nm();d?d.focus():a.$.focus();s_wrd(a,!0,b.event().detail.data.aDa);a.Da||(c=a.$.offsetWidth-a.$.clientWidth,0<c&&s_Id(a.$,c+s_r(a.$).width),a.Da=!0);s_4i(a.Ca);a.ka.$.get("animated")&&(new s_N2(a.$,d,a.ha,b.event().detail.W2,a.ka.getType())).play().then(s_c(function(){d?d.focus():
this.$.focus()},a))},s_wrd=function(a,b,c){if(a.ka.$.get("log_visibility_change")&&s_Qe(a.$)&&(!c||s_Qe(c))){if(b||!a.qa&&a.Ga)s_z(c,[a.$],[b]),a.Ga=b;a.qa=!1}},s_O2=function(a){return s_ij(s_X(a.Fa,"ApRJQKtFf4g"))},s_vrd=function(a){a.ma||(a.ma=s_O2(a).PP().firstElementChild);return a.ma},s_urd=function(a,b){b&&2==b.getType()&&s_g(a.Ea,function(a){var c=b.W$a()||b.getContent();s_o(s_X(a.Fa,"c9aCVjs5-OM"),c)})};
var s_yrd=function(a){this.$=a};s_yrd.prototype.getType=function(){return this.$.get("type")};var s_zrd=function(a){s_W.call(this,a)};s_f(s_zrd,s_W);s_zrd.prototype.Og=function(){return s_X(this,"6y9ZvyRIOWM")};var s_Ard=function(a){s_W.call(this,a)};s_f(s_Ard,s_W);
s_U(function(a){s_T(a,"t-HTuKV_b0rvs",s_trd,s_yrd,s_zrd,function(a,c,d){s_trd.call(a,c,d)});s_S(a,"geeXt7eMCvY",function(a,c){s_srd(a);c=c.event();var b=c.detail.data;s_urd(a,b.trigger);if(!a.ka.$.get("ignore_same_selection")||b.H0||2!=b.trigger.getType()){var e=s_O2(a);a.qa=!0;e.setVisible(!1);e.PP().focus();s_hj(a,c.detail.type,b)}});s_S(a,"68lrCU_57A0",function(a){s_srd(a);var b=s_ij(a.$),d=b.nm();if(d){if(b.Ja(d),b.Ia(d,!0),d&&1==a.ka.getType()&&s_O2(a).Ua()&&!a.ka.$.get("show_button_as_header")){var b=
s_O2(a).PP().getBoundingClientRect(),d=d.getBoundingClientRect(),e=a.$.getBoundingClientRect(),b=(b.height-d.height)/2+e.top-d.top;s_O2(a).dza(b)}}else s_O2(a).dza(0)});s_S(a,"XD3wZkKN3Ps",function(a,c){a.Ea.push(s_ij(c.event().target))});s_S(a,"EaFH8rK9Nkk",function(a,c){s_xrd(a,c)});s_S(a,"6NU-TVOL7Ps",function(a,c){if(a.ha){s_q(s_V(a),{width:a.Ja,height:a.Ia});var b=s_O2(a).PP(),e=s_vrd(a);b.appendChild(e)}s_ij(a.$).Ja(null);s_wrd(a,!1,c.event().detail.data.aDa);s_5i(a.Ca)});s_S(a,"bNPAC5sj7ds", function(a){s_O2(a).setVisible(!1)})});s_U(function(a){s_T(a,"t-PVnCDFJa4eM",s_qrd,null,s_Ard,function(a,c,d){s_qrd.call(a,d)})});


s_C("sdpm");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy164");var s_yva=[1,2],s_qp=function(){this.$={};this.ka=0;this.qa=null;this.ha=this.ma=0};s_qp.prototype.hasListener=function(a){return!!this.$[s_ra(a)]};
s_qp.prototype.listen=function(a,b,c,d,e){c=c||s_yva;var f=s_ra(a);if(e)this.unlisten(a);else if(this.$[f])throw Error("xd");this.$[f]={element:a,p0:b,eventTypes:c,context:d};s_Ya(c,1)&&(0==this.ka&&(d&&s_pa(d.Zga)&&d.Zga()?this.qa=s_p(window,"mousedown",this.Ea,!0,this):s_p(window,"click",this.Ea,!0,this)),this.ka++);s_Ya(c,2)&&(0==this.ma&&s_p(window,"keydown",this.Ca,!0,this),this.ma++);s_Ya(c,3)&&(0==this.ha&&s_p(window,"focus",this.Wa,!0,this),this.ha++)};
s_qp.prototype.unlisten=function(a){(a=this.$[s_ra(a)])&&s_zva(this,a)};var s_zva=function(a,b){s_Ya(b.eventTypes,1)&&(a.ka--,0==a.ka&&a.qa&&(a.qa=null));s_Ya(b.eventTypes,2)&&a.ma--;s_Ya(b.eventTypes,3)&&a.ha--;delete a.$[s_ra(b.element)]};s_qp.prototype.yd=function(a){(a=this.$[s_ra(a)])&&s_Ava(this,a,0)};var s_Ava=function(a,b,c,d){try{var e=b.p0.call(b.context,c,d)}catch(f){s_me(f)}!1!==e&&s_zva(a,b)};
s_qp.prototype.Ea=function(a){if("attention-ping"!=a.target.id)for(var b in this.$){var c=this.$[b];s_Ya(c.eventTypes,1)&&!s_Mc(c.element,a.target)&&s_Ava(this,c,1,a.target)}};s_qp.prototype.Ca=function(a){if(27==a.keyCode){for(var b in this.$){var c=this.$[b];s_Ya(c.eventTypes,2)&&s_Ava(this,c,2)}a.stopPropagation();a.preventDefault()}};s_qp.prototype.Wa=function(a){for(var b in this.$){var c=this.$[b];!s_Ya(c.eventTypes,3)||s_Aba(a.target)&&s_Mc(c.element,a.target)||s_Ava(this,c,3,a.target)}}; var s_rp=new s_qp,s_sp=s_c(s_rp.listen,s_rp),s_tp=s_c(s_rp.unlisten,s_rp),s_Bva=s_c(s_rp.yd,s_rp),s_Cva=s_c(s_rp.hasListener,s_rp);

s_C("sy164");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy226");var s_Bu=function(a,b,c,d,e,f,g,k,l){var m=s_cOa(c),n=s_Ld(a),ba=s_Bd(a);ba&&n.wga(s_cca(ba));var ba=s_mc(a),t=s_mc(c);if(ba.$!=t.$){ba=ba.$.body;var t=s_Wc(t),w=new s_ec(0,0),B=s_xc(s_lc(ba));if(s_Oaa(B,"parent")){var G=ba;do{var I=B==t?s_Ad(G):s_kca(G);w.x+=I.x;w.y+=I.y}while(B&&B!=t&&B!=B.parent&&(G=B.frameElement)&&(B=B.parent))}ba=s_hc(w,s_Ad(ba));n.left+=ba.x;n.top+=ba.y}a=s_dOa(a,b);b=n.left;a&4?b+=n.width:a&2&&(b+=n.width/2);n=new s_ec(b,n.top+(a&1?n.height:0));n=s_hc(n,m);e&&(n.x+=(a&4?-1:
1)*e.x,n.y+=(a&1?-1:1)*e.y);var N;if(g)if(l)N=l;else if(N=s_Bd(c))N.top-=m.y,N.right-=m.x,N.bottom-=m.y,N.left-=m.x;return s_Au(n,c,d,f,N,g,k)},s_cOa=function(a){var b;if(a=a.offsetParent){var c="HTML"==a.tagName||"BODY"==a.tagName;c&&"static"==s_wd(a)||(b=s_Ad(a),c||(b=s_hc(b,new s_ec(s_Bl(a),a.scrollTop))))}return b||new s_ec},s_Au=function(a,b,c,d,e,f,g){a=a.clone();var k=s_dOa(b,c);c=s_r(b);g=g?g.clone():c.clone();a=a.clone();g=g.clone();var l=0;if(d||0!=k)k&4?a.x-=g.width+(d?d.right:0):k&2?a.x-=
g.width/2:d&&(a.x+=d.left),k&1?a.y-=g.height+(d?d.bottom:0):d&&(a.y+=d.top);if(f){if(e){d=a;k=g;l=0;65==(f&65)&&(d.x<e.left||d.x>=e.right)&&(f&=-2);132==(f&132)&&(d.y<e.top||d.y>=e.bottom)&&(f&=-5);d.x<e.left&&f&1&&(d.x=e.left,l|=1);if(f&16){var m=d.x;d.x<e.left&&(d.x=e.left,l|=4);d.x+k.width>e.right&&(k.width=Math.min(e.right-d.x,m+k.width-e.left),k.width=Math.max(k.width,0),l|=4)}d.x+k.width>e.right&&f&1&&(d.x=Math.max(e.right-k.width,e.left),l|=1);f&2&&(l|=(d.x<e.left?16:0)|(d.x+k.width>e.right?
32:0));d.y<e.top&&f&4&&(d.y=e.top,l|=2);f&32&&(m=d.y,d.y<e.top&&(d.y=e.top,l|=8),d.y+k.height>e.bottom&&(k.height=Math.min(e.bottom-d.y,m+k.height-e.top),k.height=Math.max(k.height,0),l|=8));d.y+k.height>e.bottom&&f&4&&(d.y=Math.max(e.bottom-k.height,e.top),l|=2);f&8&&(l|=(d.y<e.top?64:0)|(d.y+k.height>e.bottom?128:0));e=l}else e=256;l=e}f=new s_pd(0,0,0,0);f.left=a.x;f.top=a.y;f.width=g.width;f.height=g.height;e=l;if(e&496)return e;s_xd(b,s_rd(f));g=s_1oa(f);s_jc(c,g)||(c=g,a=s_Iba(s_mc(s_lc(b))),
!s_Nb||s_Xb("10")||a&&s_Xb("8")?(b=b.style,s_Pb?b.MozBoxSizing="border-box":s_Qb?b.WebkitBoxSizing="border-box":b.boxSizing="border-box",b.width=Math.max(c.width,0)+"px",b.height=Math.max(c.height,0)+"px"):(g=b.style,a?(a=s_Td(b),b=s_Cd(b),g.pixelWidth=c.width-b.left-a.left-a.right-b.right,g.pixelHeight=c.height-b.top-a.top-a.bottom-b.bottom):(g.pixelWidth=c.width,g.pixelHeight=c.height)));return e},s_dOa=function(a,b){return(b&8&&s_Pd(a)?b^4:b)&-9};

s_C("sy226");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sp");var s_2sd=function(a,b){this.$=a;this.Fa=b;this.ha=s_V(this);this.ma=b.getPopup();this.ma.__owner=this.ha;this.Ea=this.qa=0;this.Wa=s_c(this.gfa,this);s_He(window,"resize",this.Wa)};s_f(s_2sd,s_h);var s_3sd=s_yva.concat([3]);s_=s_2sd.prototype;s_.Ha=function(){s_tp(this.ma);s_Ie(window,"resize",this.Wa);s_Mc(this.ha,this.ma)||this.ha.appendChild(this.ma);s_2sd.Ba.Ha.call(this)};s_.pKa=function(a,b){if(b&&s_Aba(b)&&s_Mc(this.PP(),b))return!1;this.setVisible(!1);2==a&&this.PP().focus();return!1};
s_.gfa=function(){if(this.Ua()){var a=this.getPopup(),b=this.PP(),c=new s_ec(this.qa,this.Ea),d=this.$.$.get("anchor_position"),e=this.$.$.get("popup_position"),f=s_4sd(d),g=s_4sd(e);if(5==d||2==d)d=s_r(b),c.x+=(f&4?-1:1)*Math.floor(d.width/2);if(5==e||2==e)d=s_r(a),c.x+=(g&4?1:-1)*Math.floor(d.width/2);s_Bu(b,f,a,g,c);e=null;b=s_sc();b=new s_od(0,b.width,b.height,0);c=s_5sd(this.$);if((f=this.$.$.get("constraint_element_id"))&&(this.$.$.get("constraint_x")||this.$.$.get("constraint_y")||c)){if(f=
document.getElementById(f))if(e=f.getBoundingClientRect(),e=new s_od(e.top,e.right,e.bottom,e.left),c)c=null,e.left<=b.right&&b.left<=e.right&&e.top<=b.bottom&&b.top<=e.bottom&&(c=new s_od(Math.max(e.top,b.top),Math.min(e.right,b.right),Math.min(e.bottom,b.bottom),Math.max(e.left,b.left)),c.left==c.right||c.top==c.bottom)&&(c=null),e=c}else c&&(e=b);e&&(b=parseInt(s_sd(a,"top"),10),c=parseInt(s_sd(a,"left"),10),f=s_hca(a).getBoundingClientRect(),e=new s_od(e.top-f.top,e.right-f.left,e.bottom-f.top,
e.left-f.left),f=s_r(a),f.width<=e.Ab()&&(this.$.$.get("constraint_x")||s_5sd(this.$))&&(c=Math.max(c,e.left),c=Math.min(c,e.right-f.width)),f.height<=e.wd()&&(this.$.$.get("constraint_y")||s_5sd(this.$))&&(b=Math.max(b,e.top),b=Math.min(b,e.bottom-f.height)),s_xd(a,c,b))}};s_.Ua=function(){return s_Nd(this.getPopup())};
s_.setVisible=function(a,b,c){var d=this.getPopup(),e=a!=this.Ua();s_s(d,a);if(a&&s_Mc(this.ha,d)){var f=s_i("lb");f&&f.appendChild(d)}else a||s_Mc(this.ha,d)||this.ha.appendChild(d);a&&(s_2g(this.ha,"g_popup_before_reposition"),this.gfa());e&&(a?s_sp(this.ma,this.pKa,s_3sd,this,!0):s_tp(this.ma),s_2g(this.ha,a?"g_popup_show":"g_popup_hide",{aDa:c||null},b))};s_.PP=function(){return s_X(this.Fa,"ORKVAA_LDzU")};s_.getPopup=function(){return this.ma};s_.dza=function(a){this.qa=0;this.Ea=a}; var s_4sd=function(a){var b=8;switch(a){case 2:case 1:b=8;break;case 3:b=12;break;case 5:case 4:b=9;break;case 6:b=13}return b};
var s_6sd=function(a){this.$=a},s_5sd=function(a){return a.$.get("constrain_to_viewport")},s_7sd=function(a){s_W.call(this,a)};s_f(s_7sd,s_W);s_7sd.prototype.getPopup=function(){return s_X(this,"oxZ6sQHv7j4")};s_U(function(a){s_T(a,"t-WFThJAOshrg",s_2sd,s_6sd,s_7sd,function(a,c,d){s_2sd.call(a,c,d)});s_S(a,"9D66ndlfkZ0",function(a,c){c=c.event()||void 0;a.setVisible(!a.Ua(),c,a.PP().firstElementChild);c&&c.preventDefault()})});

s_C("sp");s_E();
}catch(e){_DumpException(e)}
try{
s_D("sy455");
s_C("sy455");s_E();
}catch(e){_DumpException(e)}
try{
var s_Asd=function(a,b){this.trigger=a;this.H0=b},s_Bsd=function(){return!1},s_Csd=function(a,b){a.length&&(b%=a.length,0<b?Array.prototype.unshift.apply(a,a.splice(-b,b)):0>b&&Array.prototype.push.apply(a,a.splice(0,-b)));return a},s_32=function(a,b){this.Fa=b;this.Na=a.$.get("max_height");this.$=s_V(this);this.ma=null;this.Ca=[];this.Ma=!1;this.ha=null;this.Wa=!1;s_p(window,"resize",this.Ga,!1,this);this.Ga();this.Db=new s_hs(this.rb,1E3,this);this.ka(this.Db);this.Ea="";a=s_Sa(s_Dsd(this.Fa),function(a){return s_jj(a)});
s_kf(a).then(function(){s_22(this)},null,this)};s_f(s_32,s_h);s_32.prototype.Ha=function(){this.Wa&&s_Ye(94,s_Bsd);s_9c(window,"resize",this.Ga,!1,this)};s_32.prototype.rb=function(){this.Ea=""};
var s_22=function(a){a.Ma||(s_g(s_Dsd(a.Fa),function(a){var b=s_ij(a);if(b.Ug()&&b.isEnabled())switch(b.getType()){case 2:s_Esd(this);b.kd(!0);this.ma=a;break;case 3:b.kd(!0);this.Ca.push(a);break;default:b.kd(!1)}else b.kd(!1)},a),a.Ma=!0)},s_Esd=function(a){a.ma&&(s_ij(a.ma).kd(!1),a.ma=null)},s_Fsd=function(a,b){return!!s_Xa(s_Dsd(a.Fa),function(a){return a==b})};s_32.prototype.aka=function(a){s_22(this);s_Fsd(this,a)&&s_Gsd(this,a)};
var s_Gsd=function(a,b){var c=s_ij(b);if(c.isEnabled()){s_Hsd(a,b);if(2==c.getType()){var d=a.ma!=b;d&&(s_Esd(a),a.ma=b,c.kd(!0));s_Isd(a,c,d)}else 3==c.getType()?(d=!c.Ug(),c.kd(d),d?a.Ca.push(b):s_2a(a.Ca,b),s_Isd(a,c,!0)):s_Isd(a,c,!1);c.Ug()}},s_Isd=function(a,b,c){s_hj(a,"menu_item_selected",new s_Asd(b,c))};s_32.prototype.nm=function(){s_22(this);return this.ma};s_32.prototype.qa=function(){s_22(this);return this.Ca};
s_32.prototype.Da=function(){s_22(this);var a=this.nm();return a?s_ij(a).getContent():""};s_32.prototype.Ja=function(a){s_22(this);a&&!s_Fsd(this,a)||s_Hsd(this,a)};var s_Hsd=function(a,b){if(b){var c=s_ij(b);if(!c.isEnabled())return;c.cza(!0)}a.ha!=b&&a.ha&&s_ij(a.ha).cza(!1);a.ha=b};s_32.prototype.Ga=function(){0>this.Na||s_q(this.$,"max-height",Math.min(this.Na,Math.round(.75*window.innerHeight))+"px")};
var s_Lsd=function(a,b){if(b=b.event()){var c=b.which||b.keyCode;switch(c){case 40:case 38:case 9:var c=40==c||9==c&&!b.shiftKey,d=s_Jsd(a,c),c=(c?s_Xa:s_lha)(d,a.Za,a);s_Hsd(a,c);if(c=a.ha)a.Ia(c,void 0),c.focus();break;case 13:case 32:if(32!=c||!a.Ea){a.ha&&s_Gsd(a,a.ha);break}default:s_mi(c)&&(a.Db.start(),c=String.fromCharCode(c),a.Ea==c?c=s_Ksd(a,!0):(a.Ea+=c,c=s_Ksd(a,!1)),c&&(s_Hsd(a,c),c=a.ha))&&(a.Ia(c,void 0),c.focus())}s_3g(b);s_4g(b)}},s_Ksd=function(a,b){b=b?s_Jsd(a,!0):s_Dsd(a.Fa);return s_Xa(b,
function(a){if(this.Za(a)){a=s_ij(a).getContent();var b=this.Ea;return 0==s_Cja(b,a.substr(0,b.length))}return!1},a)},s_Jsd=function(a,b){var c=a.ha;a=s_4a(s_Dsd(a.Fa));if(c){var d=s_Wa(a,function(a){return c==a});a=s_Csd(a,b?-d-1:-d)}return a};s_32.prototype.Za=function(a){return s_ij(a).isEnabled()};
s_32.prototype.Ia=function(a,b){if(a){var c=s_r(this.$);if(c.height<this.$.scrollHeight){var d=this.$.getBoundingClientRect().top,e=s_r(a),d=a.getBoundingClientRect().top-d,f=e.height/2;d<f?this.$.scrollTop+=d-f:d+e.height>c.height-f&&(this.$.scrollTop+=d+e.height-c.height+f);b&&(this.$.scrollTop+=a.getBoundingClientRect().top-this.$.getBoundingClientRect().top-Math.floor((c.height-e.height)/2))}}};s_D("sm");
var s_Msd=function(a){this.$=a},s_Nsd=function(a){s_W.call(this,a)};s_f(s_Nsd,s_W);var s_Dsd=function(a){return s_oj(a,"ZTgA23wj-jA")};
s_U(function(a){s_T(a,"t-ftPmC9-eyZE",s_32,s_Msd,s_Nsd,function(a,c,d){s_32.call(a,c,d)});s_S(a,"Fabc-oczb5A",function(a,c){s_Lsd(a,c)});s_S(a,"H8vUkER8xS8",function(a){a.Wa||s_Xe(94,s_Bsd);a.Wa=!0});s_S(a,"qNIf1dmVF-A",function(a){a.Wa&&s_Ye(94,s_Bsd);a.Wa=!1});s_S(a,"bKnH9ONl_O8",function(a,c){var b=c.event();(b=b?b.which||b.keyCode:null)&&32==b?s_Lsd(a,c):(c=c.node())&&s_Gsd(a,c)});s_S(a,"31HJ7etxBLE",function(a,c){(c=c.node())&&s_Hsd(a,c)})});

s_C("sm");s_E();
}catch(e){_DumpException(e)}
try{
var s_12;s_D("smi");var s_wsd=function(a,b){this.Fa=b;this.ka=a;this.$=s_V(this);s_12||(s_12=s_vsd)};s_wsd.prototype.va=function(){return this.$};s_wsd.prototype.getType=function(){return this.ka.getType()};var s_xsd=function(a){a=a.ka.getType();return 1!=a&&4!=a};s_=s_wsd.prototype;s_.isEnabled=function(){return!this.$.getAttribute("disabled")};s_.jMa=function(){return 4==this.ka.getType()};
s_.setEnabled=function(a){a?this.$.removeAttribute("disabled"):this.$.setAttribute("disabled","true");s_0i(this.$,"disabled",a?"false":"true")};s_.Ug=function(){return s_v(this.$,s_12.Ix)};s_.kd=function(a){a?s_xsd(this)&&this.isEnabled()&&!s_v(this.$,s_12.Ix)&&s_w(this.$,s_12.Ix):s_x(this.$,s_12.Ix);s_xsd(this)&&this.isEnabled()&&s_0i(this.$,"checked",a?"true":"false")};s_.cza=function(a){a?this.isEnabled()&&s_w(this.$,s_12.Bz):s_x(this.$,s_12.Bz)};s_.getContent=function(){return s_Qc(this.Fa.getItem())}; s_.W$a=function(){return s_t(this.$,"shortLabel")};
var s_ysd=function(a){this.$=a};s_ysd.prototype.getType=function(){return this.$.get("type")};var s_zsd=function(a){s_W.call(this,a)};s_f(s_zsd,s_W);s_zsd.prototype.getItem=function(){return s_X(this,"NJCQz-plXrk")};var s_vsd={fSa:"oLMvxj8HcwN__allow-select",Bz:"oLMvxj8HcwN__highlighted",GSa:"oLMvxj8HcwN__item-content",Ix:"oLMvxj8HcwN__selected"};s_U(function(a){s_T(a,"t--Xn6T8uviho",s_wsd,s_ysd,s_zsd,function(a,c,d){s_wsd.call(a,c,d)})});

s_C("smi");s_E();
}catch(e){_DumpException(e)}
try{
s_D("me");var s_p5=function(a){a=a.$.$(s_vId,"ec");this.qa=s_K(a,1)||!1;var b=s_K(a,2)||!1;this.ha=this.qa&&b;b=s_K(a,4);a=s_K(a,5);this.Wa=null!=b?b:1068;this.Ca=null!=a?a:1156;s_c(this.ma,this);this.ha&&(this.$=s_ff(null,s_c(this.Ea,this),!0),s_p(window,"resize",this.$,!1,this),this.$())};s_f(s_p5,s_h);s_p5.prototype.Ha=function(){this.ha&&s_9c(window,"resize",this.$,!1,this)};s_p5.prototype.Ea=function(){s_wId(this,s_i("rhs_block"));s_wId(this,s_i("nyc"));s_u(60)};s_p5.prototype.$=null; s_p5.prototype.ma=function(){if(!this.qa)return 0;var a=document.body.offsetWidth,b=this.Wa;return a>=this.Ca?5:a>=b?4:3};var s_wId=function(a,b){b&&(a=a.ma(),s_y(b,"rhstc3",4>a),s_y(b,"rhstc4",4==a),s_y(b,"rhstc5",4<a))};
var s_vId=function(a){s_I(this,a,0,-1,null,null)};s_f(s_vId,s_H);var s_xId=function(a){this.$=a};s_U(function(a){s_T(a,"t-5RRekjfu2Ys",s_p5,s_xId,null,function(a,c){s_p5.call(a,c)})});
s_C("me");s_E();
}catch(e){_DumpException(e)}
// Google Inc.
